EXTRAFLAGS+=-I..
EXTRAFLAGS+=-I../../libpluto
EXTRAFLAGS+=-I../../libpluto/lp67-ike2ops
include ../../libpluto/lp67-ike2ops/Makefile

EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/crypto.o
EXTRALIBS+=${CRYPTOLIBS} ${LIBOSWKEYS} ${LIBOSWLOG} ${LIBOPENSWAN}

# Local Variables:
# gdb-command: ""
# End Variables:
#
