# -*- makefile -*-
CONNNAME=parker
ENDNAME=jamesjohnson
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}
UNITTEST1PCAP=OUTPUT/nattR2.pcap
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME} ${UNITTEST1PCAP} ../lp62-nattR1/nattI1.pcap nattI2.pcap

TESTNAME=nattR2

PCAPDEPENDENCIES = ../lp63-nattI2/OUTPUT/nattI2.pcap
include ../Makefile.pcapupdate

pcapupdate: ${PCAPDEPENDENCIES}
	cp ../lp63-nattI2/OUTPUT/nattI2.pcap nattI2.pcap




