.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "IPSEC.CONF" "5" "03/23/2010" "30 May 2008" "30 May 2008"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ipsec.conf \- IPsec configuration and connections
.SH "DESCRIPTION"
.PP
The optional
\fIipsec.conf\fR
file specifies most configuration and control information for the Openswan IPsec subsystem. (The major exception is secrets for authentication; see
\fBipsec.secrets\fR(5).) Its contents are not security\-sensitive
\fIunless\fR
manual keying is being done for more than just testing, in which case the encryption/authentication keys in the descriptions for the manually\-keyed connections are very sensitive (and those connection descriptions are probably best kept in a separate file, via the include facility described below).
.PP
The file is a text file, consisting of one or more
\fIsections\fR. White space followed by
\fI#\fR
followed by anything to the end of the line is a comment and is ignored, as are empty lines which are not within a section.
.PP
A line which contains
\fIinclude\fR
and a file name, separated by white space, is replaced by the contents of that file, preceded and followed by empty lines. If the file name is not a full pathname, it is considered to be relative to the directory containing the including file. Such inclusions can be nested. Only a single filename may be supplied, and it may not contain white space, but it may include shell wildcards (see
\fBsh\fR(1)); for example:
.PP
\fIinclude\fR\fIipsec.*.conf\fR
.PP
The intention of the include facility is mostly to permit keeping information on connections, or sets of connections, separate from the main configuration file. This permits such connection descriptions to be changed, copied to the other security gateways involved, etc., without having to constantly extract them from the configuration file and then insert them back into it. Note also the
\fIalso\fR
and
\fIalsoflip\fR
parameters (described below) which permit splitting a single logical section (e.g. a connection description) into several actual sections.
.PP
The first significant line of the file must specify the version of this specification that it conforms to:
.PP
\fIversion 2\fR
.PP
A section begins with a line of the form:
.PP
\fItype\fR\fIname\fR
.PP
where
\fItype\fR
indicates what type of section follows, and
\fIname\fR
is an arbitrary name which distinguishes the section from others of the same type. (Names must start with a letter and may contain only letters, digits, periods, underscores, and hyphens.) All subsequent non\-empty lines which begin with white space are part of the section; comments within a section must begin with white space too. There may be only one section of a given type with a given name.
.PP
Lines within the section are generally of the form
.PP
\ \ \ \ \ \fIparameter\fR\fI=\fR\fIvalue\fR
.PP
(note the mandatory preceding white space). There can be white space on either side of the
\fI=\fR. Parameter names follow the same syntax as section names, and are specific to a section type. Unless otherwise explicitly specified, no parameter name may appear more than once in a section.
.PP
An empty
\fIvalue\fR
stands for the system default value (if any) of the parameter, i.e. it is roughly equivalent to omitting the parameter line entirely. A
\fIvalue\fR
may contain white space only if the entire
\fIvalue\fR
is enclosed in double quotes (\fI"\fR); a
\fIvalue\fR
cannot itself contain a double quote, nor may it be continued across more than one line.
.PP
Numeric values are specified to be either an \(lqinteger\(rq (a sequence of digits) or a \(lqdecimal number\(rq (sequence of digits optionally followed by `.' and another sequence of digits).
.PP
There is currently one parameter which is available in any type of section:
.TP
\fIalso\fR
the value is a section name; the parameters of that section are appended to this section, as if they had been written as part of it. The specified section must exist, must follow the current one, and must have the same section type. (Nesting is permitted, and there may be more than one
\fIalso\fR
in a single section, although it is forbidden to append the same section more than once.) This allows, for example, keeping the encryption keys for a connection in a separate file from the rest of the description, by using both an
\fIalso\fR
parameter and an
\fIinclude\fR
line. (Caution, see BUGS below for some restrictions.)
.TP
\fIalsoflip\fR
can be used in a
\fIconn\fR
section. It acts like an
\fIalso\fR
that flips the referenced section's entries left\-for\-right.
.PP
Parameter names beginning with
\fIx\-\fR
(or
\fIX\-\fR, or
\fIx_\fR, or
\fIX_\fR) are reserved for user extensions and will never be assigned meanings by IPsec. Parameters with such names must still observe the syntax rules (limits on characters used in the name; no white space in a non\-quoted value; no newlines or double quotes within the value). All other as\-yet\-unused parameter names are reserved for future IPsec improvements.
.PP
A section with name
\fI%default\fR
specifies defaults for sections of the same type. For each parameter in it, any section of that type which does not have a parameter of the same name gets a copy of the one from the
\fI%default\fR
section. There may be multiple
\fI%default\fR
sections of a given type, but only one default may be supplied for any specific parameter name, and all
\fI%default\fR
sections of a given type must precede all non\-\fI%default\fR
sections of that type.
\fI%default\fR
sections may not contain
\fIalso\fR
or
\fIalsoflip\fR
parameters.
.PP
Currently there are two types of section: a
\fIconfig\fR
section specifies general configuration information for IPsec, while a
\fIconn\fR
section specifies an IPsec connection.
.SH "CONN SECTIONS"
.PP
A
\fIconn\fR
section contains a
\fIconnection specification\fR, defining a network connection to be made using IPsec. The name given is arbitrary, and is used to identify the connection to
\fBipsec_auto\fR(8)
and
\fBipsec_manual\fR(8). Here's a simple example:
.sp
.nf

\fI
conn snt
	left=10.11.11.1
	leftsubnet=10.0.1.0/24
	leftnexthop=172.16.55.66
	leftsourceip=10.0.1.1
	right=192.168.22.1
	rightsubnet=10.0.2.0/24
	rightnexthop=172.16.88.99
	rightsourceip=10.0.2.1
	keyingtries=%forever
\fR
.fi
.sp
.PP
A note on terminology... In automatic keying, there are two kinds of communications going on: transmission of user IP packets, and gateway\-to\-gateway negotiations for keying, rekeying, and general control. The data path (a set of \(lqIPsec SAs\(rq) used for user packets is herein referred to as the \(lqconnection\(rq; the path used for negotiations (built with \(lqISAKMP SAs\(rq) is referred to as the \(lqkeying channel\(rq.
.PP
To avoid trivial editing of the configuration file to suit it to each system involved in a connection, connection specifications are written in terms of
\fIleft\fR
and
\fIright\fR
participants, rather than in terms of local and remote. Which participant is considered
\fIleft\fR
or
\fIright\fR
is arbitrary; IPsec figures out which one it is being run on based on internal information. This permits using identical connection specifications on both ends. There are cases where there is no symmetry; a good convention is to use
\fIleft\fR
for the local side and
\fIright\fR
for the remote side (the first letters are a good mnemonic).
.PP
Many of the parameters relate to one participant or the other; only the ones for
\fIleft\fR
are listed here, but every parameter whose name begins with
\fIleft\fR
has a
\fIright\fR
counterpart, whose description is the same but with
\fIleft\fR
and
\fIright\fR
reversed.
.PP
Parameters are optional unless marked \(lq(required)\(rq; a parameter required for manual keying need not be included for a connection which will use only automatic keying, and vice versa.
.SS "CONN PARAMETERS:  GENERAL"
.PP
The following parameters are relevant to both automatic and manual keying. Unless otherwise noted, for a connection to work, in general it is necessary for the two ends to agree exactly on the values of these parameters.
.TP
\fIconnaddrfamily\fR
the connection addrress family of the connection; currently the accepted values are
\fIipv4\fR
(the default); or
\fIipv6\fR,
.sp
The ipv6 family is currently only supported using the NETKEY stack.
.TP
\fItype\fR
the type of the connection; currently the accepted values are
\fItunnel\fR
(the default) signifying a host\-to\-host, host\-to\-subnet, or subnet\-to\-subnet tunnel;
\fItransport\fR, signifying host\-to\-host transport mode;
\fIpassthrough\fR, signifying that no IPsec processing should be done at all;
\fIdrop\fR, signifying that packets should be discarded; and
\fIreject\fR, signifying that packets should be discarded and a diagnostic ICMP returned.
.TP
\fIleft\fR
(required) the IP address of the left participant's public\-network interface, in any form accepted by
\fBipsec_ttoaddr\fR(3). Currently, IPv4 and IPv6 IP addresses are supported. There are several magic values. If it is
\fI%defaultroute\fR, and the
\fIconfig\fR\fIsetup\fR
section's,
\fIinterfaces\fR
specification contains
\fI%defaultroute,\fR\fIleft\fR
will be filled in automatically with the local address of the default\-route interface (as determined at IPsec startup time); this also overrides any value supplied for
\fIleftnexthop\fR. (Either
\fIleft\fR
or
\fIright\fR
may be
\fI%defaultroute\fR, but not both.) The value
\fI%any\fR
signifies an address to be filled in (by automatic keying) during negotiation. The value
\fI%opportunistic\fR
signifies that both
\fIleft\fR
and
\fIleftnexthop\fR
are to be filled in (by automatic keying) from DNS data for
\fIleft\fR's client. The values
\fI%group\fR
and
\fI%opportunisticgroup\fR
makes this a policy group conn: one that will be instantiated into a regular or opportunistic conn for each CIDR block listed in the policy group file with the same name as the conn.
.sp
If using IP addresses in combination with NAT, always use the actual local machine's (NAT'ed) IP address, and if the remote (eg right=) is NAT'ed as well, the remote's public (\fInot\fR
NAT'ed) IP address. Note that this makes the configuration no longer symmetrical on both sides, so you cannot use an identical configuration file on both hosts.
.TP
\fIleftsubnet\fR
private subnet behind the left participant, expressed as
\fInetwork\fR\fI/\fR\fInetmask\fR
(actually, any form acceptable to
\fBipsec_ttosubnet\fR(3)); Currentlly, IPv4 and IPv6 ranges are supported. if omitted, essentially assumed to be
\fIleft\fR\fI/32\fR, signifying that the left end of the connection goes to the left participant only
.TP
\fIleftsubnets\fR
specify multiple private subnets behind the left participant, expressed as {
\fInetworkA\fR\fI/\fR\fInetmaskA\fR\fInetworkB\fR\fI/\fR\fInetmaskB\fR\fI[...]\fR
} If both a leftsubnets= and rightsubnets= is defined, all combinations of subnet tunnels will be instantiated. You cannot use leftsubnet and leftsubnets together. For examples see
\fItesting/pluto/multinet\-*\fR.
.TP
\fIleftprotoport\fR
allowed protocols and ports over connection, also called Port Selectors. The argument is in the form
\fIprotocol\fR, which can be a number or a name that will be looked up in
\fI/etc/protocols\fR, such as
\fIleftprotoport=icmp\fR, or in the form of
\fIprotocol/port\fR, such as
\fItcp/smtp\fR. Ports can be defined as a number (eg. 25) or as a name (eg smtp) which will be looked up in
\fI/etc/services\fR. A special keyword
\fI%any\fR
can be used to allow all ports of a certain protocol. The most common use of this option is for L2TP connections to only allow l2tp packets (UDP port 1701), eg:
\fIleftprotoport=17/1701\fR. Some clients, notably older Windows XP and some Mac OSX clients, use a random high port as source port. In those cases
\fIrightprotoport=17/%any\fR
can be used to allow all UDP traffic on the connection. Note that this option is part of the proposal, so it cannot be arbitrarily left out if one end does not care about the traffic selection over this connection \- both peers have to agree. The Port Selectors show up in the output of
\fIipsec eroute\fR
and
\fIipsec auto \-\-status\fR
eg:\fI"l2tp": 193.110.157.131[@aivd.xelernace.com]:7/1701...%any:17/1701\fR
This option only filters outbound traffic. Inbound traffic selection must still be based on firewall rules activated by an updown script. The variablees $PLUTO_MY_PROTOCOL, $PLUTO_PEER_PROTOCOL, $PLUTO_MY_PORT, and $PLUTO_PEER_PORT are available for use in
\fIupdown\fR
scripts. Older workarounds for bugs involved a setting of
\fI17/0\fR
to denote
\fIany single UDP port\fR
(not UDP port 0). Some clients, most notably OSX, uses a random high port, instead of port 1705 for L2TP.
.TP
\fIleftnexthop\fR
next\-hop gateway IP address for the left participant's connection to the public network; defaults to
\fI%direct\fR
(meaning
\fIright\fR). If the value is to be overridden by the
\fIleft=%defaultroute\fR
method (see above), an explicit value must
\fInot\fR
be given. If that method is not being used, but
\fIleftnexthop\fR
is
\fI%defaultroute\fR, and
\fIinterfaces=%defaultroute\fR
is used in the
\fIconfig\fR\fIsetup\fR
section, the next\-hop gateway address of the default\-route interface will be used. The magic value
\fI%direct\fR
signifies a value to be filled in (by automatic keying) with the peer's address. Relevant only locally, other end need not agree on it.
.TP
\fIleftsourceip\fR
the IP address for this host to use when transmitting a packet to the other side of this link. Relevant only locally, the other end need not agree. This option is used to make the gateway itself use its internal IP, which is part of the leftsubnet, to communicate to the rightsubnet or right. Otherwise, it will use its
\fInearest\fR
IP address, which is its public IP address. This option is mostly used when defining subnet\-subnet connections, so that the gateways can talk to each other and the subnet at the other end, without the need to build additional host\-subnet, subnet\-host and host\-host tunnels. Both IPv4 and IPv6 addresses are supported.
.TP
\fIleftupdown\fR
what \(lqupdown\(rq script to run to adjust routing and/or firewalling when the status of the connection changes (default
\fIipsec _updown\fR). May include positional parameters separated by white space (although this requires enclosing the whole string in quotes); including shell metacharacters is unwise. An example to enable routing when using the NETKEY stack, one can use:
.sp
leftupdown="ipsec _updown \-\-route yes"
.sp
See
\fBipsec_pluto\fR(8)
for details. Relevant only locally, other end need not agree on it.
.TP
\fIleftfirewall\fR
This option is obsolete and should not used anymore.
.PP
If one or both security gateways are doing forwarding firewalling (possibly including masquerading), and this is specified using the firewall parameters, tunnels established with IPsec are exempted from it so that packets can flow unchanged through the tunnels. (This means that all subnets connected in this manner must have distinct, non\-overlapping subnet address blocks.) This is done by the default
\fIupdown\fR
script (see
\fBipsec_pluto\fR(8)).
.PP
The implementation of this makes certain assumptions about firewall setup, and the availability of the
\fILinux Advanced Routing\fR
tools. In situations calling for more control, it may be preferable for the user to supply his own
\fIupdown\fR
script, which makes the appropriate adjustments for his system.
.SS "CONN PARAMETERS:  AUTOMATIC KEYING"
.PP
The following parameters are relevant only to automatic keying, and are ignored in manual keying. Unless otherwise noted, for a connection to work, in general it is necessary for the two ends to agree exactly on the values of these parameters.
.TP
\fIauto\fR
what operation, if any, should be done automatically at IPsec startup; currently\-accepted values are
\fIadd\fR
(signifying an
\fIipsec auto\fR\fB\-\-add\fR),
\fIroute\fR
(signifying that plus an
\fIipsec auto\fR\fB\-\-route\fR),
\fIstart\fR
(signifying that plus an
\fIipsec auto\fR\fB\-\-up\fR),
\fImanual\fR
(signifying an
\fIipsec\fR\fImanual\fR\fB\-\-up\fR), and
\fIignore\fR
(also the default) (signifying no automatic startup operation). See the
\fIconfig\fR\fIsetup\fR
discussion below. Relevant only locally, other end need not agree on it (but in general, for an intended\-to\-be\-permanent connection, both ends should use
\fIauto=start\fR
to ensure that any reboot causes immediate renegotiation).
.TP
\fIauthby\fR
how the two security gateways should authenticate each other; acceptable values are
\fIsecret\fR
for shared secrets,
\fIrsasig\fR
for RSA digital signatures (the default),
\fIsecret|rsasig\fR
for either, and
\fInever\fR
if negotiation is never to be attempted or accepted (useful for shunt\-only conns). Digital signatures are superior in every way to shared secrets.
.TP
\fIike\fR
IKE encryption/authentication algorithm to be used for the connection (phase 1 aka ISAKMP SA). The format is
\fI"cipher\-hash;modpgroup, cipher\-hash;modpgroup, ..."\fR
Any left out option will be filled in with all allowed default options. Multiple proposals are seperated by a comma. If an
\fIike=\fR
line is specified, no other received proposals will be accepted. Formerly there was a distinction (by using a
\fI"!"\fR
symbol) between "strict mode" or not. That mode has been obsoleted. If an
\fIike=\fR
option is specified, the mode is always strict, meaning no other received proposals will be accepted. Some examples are
\fIike=3des\-sha1,aes\-sha1\fR,
\fIike=aes\fR,
\fIike=aes128\-md5;modp2048\fR,
\fIike=aes128\-sha1;dh22\fR,
\fIike=3des\-md5;modp1024,aes\-sha1;modp1536\fR
or
\fIike=modp1536\fR. The options must be suitable as a value of
\fBipsec_spi\fR(8)'s
\fB\-\-ike\fR
option. The default is to use IKE, and to allow all combinations of:
.sp
.nf
\fI
                cipher:                 3des or aes
                hash:                   sha1 or md5
                pfsgroup (DHgroup):     modp1024 or modp1536
\fR
.fi
.sp
If Openswan was compiled with extra INSECURE and BROKEN options, then the des (1des) and null cipher, as well as modp768 are available. This turns your VPN into a joke. Do not enable these options.
.sp
If openswan was compiled with USE_MODP_RFC5114 support, then Diffie\-Hellman groups 22, 23 and 24 are also implemented as per RFC\-5114. Instead of the modp key syntax, use the "dh" keyword, for example
\fIike=3des\-sha1;dh23\fR
.TP
\fIphase2\fR
Sets the type of SA that will be produced. Valid options are:
\fIesp\fR
for encryption (the default), and
\fIah\fR
for authentication only.
.TP
\fIphase2alg\fR
Specifies the algorithms that will be offered/accepted for a phase2 negotiation. If not specified, a secure set of defaults will be used. Sets are seperated using comma's.
.sp
The default values are the same as for ike= Note also that not all ciphers available to the kernel (eg through CryptoAPI) are necessarilly supported here.
.sp
The format for ESP is ENC\-AUTH followed by an optional PFSgroup. For instance, "3des\-md5" or "aes256\-sha1;modp2048" or "aes\-sha1,aes\-md5".
.sp
For RFC\-5114 DH groups, use the "dh" keyword, eg "aes256\-sha1;dh23"
.sp
The format for AH is AUTH followed by an optional PFSgroup. For instance, "md5" or "sha1;modp1536".
.sp
A special case is AES CCM, which uses the syntax of "phase2alg=aes_ccm_a\-152\-null"
.TP
\fIesp\fR
This option is obsolete. Please use
\fIphase2alg\fR
instead.
.TP
\fIah\fR
AH authentication algorithm to be used for the connection, e.g here.
\fIhmac\-md5\fR
The options must be suitable as a value of
\fBipsec_spi\fR(8)'s
\fB\-\-ah\fR
option. The default is not to use AH. If for some (invalid) reason you still think you need AH, please use esp with the null encryption cipher instead. Note also that not all ciphers available to the kernel (eg through CryptoAPI) are necessarilly supported here.
.TP
\fIikev2\fR
IKEv2 (RFC4309) settings to be used. Currently the accepted values are
\fIpermit\fR, (the default) signifying no IKEv2 should be transmitted, but will be accepted if the other ends initiates to us with IKEv2;
\fInever\fR
or
\fIno\fR
signifying no IKEv2 negotiation should be transmitted or accepted;
\fIpropose\fR
or
\fIyes\fR
signifying that we permit IKEv2, and also use it as the default to initiate;
\fIinsist\fR, signifying we only accept and receive IKEv2 \- IKEv1 negotiations will be rejected.
.sp
If the ikev2= setting is set to
\fIpermit\fR
or
\fIpropose\fR, Openswan will try and detect a "bid down" attack from IKEv2 to IKEv1. Since there is no standard for transmitting the IKEv2 capability with IKEv1, Openswan uses a special Vendor ID "CAN\-IKEv2". If a fall back from IKEv2 to IKEv1 was detected, and the IKEv1 negotiation contains Vendor ID "CAN\-IKEv2", Openswan will immediately attempt and IKEv2 rekey and refuse to use the IKEv1 connection. With an ikev2= setting of
\fIinsist\fR, no IKEv1 negotiation is allowed, and no bid down attack is possible.
.TP
\fIleftid\fR
how the left participant should be identified for authentication; defaults to
\fIleft\fR. Can be an IP address (in any
\fBipsec_ttoaddr\fR(3)
syntax) or a fully\-qualified domain name preceded by
\fI@\fR
(which is used as a literal string and not resolved). The magic value
\fI%fromcert\fR
causes the ID to be set to a DN taken from a certificate that is loaded. Prior to 2.5.16, this was the default if a certificate was specified. The magic value
\fI%none\fR
sets the ID to no ID. This is included for completeness, as the ID may have been set in the default conn, and one wishes for it to default instead of being explicitly set. The magic value
\fI%myid\fR
stands for the current setting of
\fImyid\fR. This is set in
\fIconfig setup\fR
or by
\fBipsec_whack\fR(8)), or, if not set, it is the IP address in
\fI%defaultroute\fR
(if that is supported by a TXT record in its reverse domain), or otherwise it is the system's hostname (if that is supported by a TXT record in its forward domain), or otherwise it is undefined.
.TP
\fIleftrsasigkey\fR
the left participant's public key for RSA signature authentication, in RFC 2537 format using
\fBipsec_ttodata\fR(3)
encoding. The magic value
\fI%none\fR
means the same as not specifying a value (useful to override a default). The value
\fI%dnsondemand\fR
(the default) means the key is to be fetched from DNS at the time it is needed. The value
\fI%dnsonload\fR
means the key is to be fetched from DNS at the time the connection description is read from
\fIipsec.conf\fR; currently this will be treated as
\fI%none\fR
if
\fIright=%any\fR
or
\fIright=%opportunistic\fR. The value
\fI%dns\fR
is currently treated as
\fI%dnsonload\fR
but will change to
\fI%dnsondemand\fR
in the future. The identity used for the left participant must be a specific host, not
\fI%any\fR
or another magic value. The value
\fI%cert\fR
will load the information required from a certificate defined in
\fI%leftcert\fR
and automatically define leftid for you.
\fICaution:\fR
if two connection descriptions specify different public keys for the same
\fIleftid\fR, confusion and madness will ensue.
.TP
\fIleftrsasigkey2\fR
if present, a second public key. Either key can authenticate the signature, allowing for key rollover.
.TP
\fIleftcert\fR
If you are using
\fIleftrsasigkey=%cert\fR
this defines the certificate you would like to use. It should point to a X.509 encoded certificate file. If you do not specify a full pathname, by default it will look in /etc/ipsec.d/certs. If openswan has been compiled with
\fIUSE_LIBNSS=true\fR, then openswan will also check the NSS database for RSA keys. These can be software or hardware.
.TP
\fIleftca\fR
specifies the authorized Certificate Agency (CA) that signed the certificate of the peer. If undefined, it defaults to the CA that signed the certificate specified in
\fIleftcert\fR. The special
\fIrightca=%same\fR
is implied when not specifying a
\fIrightca\fR
and means that only peers with certificates signed by the same CA as the leftca will be allowed. This option is only useful in complex multi CA certificate situations. When using a single CA, it can be safely omitted for both left and right.
.TP
\fIleftsendcert\fR
This option configures when Openswan will send X.509 certificates to the remote host. Acceptable values are
\fIyes|always\fR
(signifying that we should always send a certificate),
\fIifasked\fR
(signifying that we should send a certificate if the remote end asks for it), and
\fIno|never\fR
(signifying that we will never send a X.509 certificate). The default for this option is
\fIifasked\fR
which may break compatibility with other vendor's IPSec implementations, such as Cisco and SafeNet. If you find that you are getting errors about no ID/Key found, you likely need to set this to
\fIalways\fR. This per\-conn option replaces the obsolete global
\fInocrsend\fR
option.
.TP
\fIleftxauthserver\fR
Left is an XAUTH server. This can use PAM for authentication or md5 passwords in
\fI/etc/ipsec.d/passwd\fR. These are additional credentials to verify the user identity, and should not be confused with the XAUTH
\fIgroup secret\fR, which is just a regular PSK defined in
\fIipsec.secrets\fR. The other side of the connection should be configured as
\fIrightxauthclient\fR. XAUTH connections cannot rekey, so
\fIrekey=no\fR
should be specified in this conn. For further details on how to compile and use XAUTH, see README.XAUTH. Acceptable values are
\fIyes\fR
or
\fIno\fR
(the default).
.TP
\fIleftxauthclient\fR
Left is an XAUTH client. The xauth connection will have to be started interactively and cannot be configured using
\fIauto=start\fR. Instead, it has to be started from the commandline using
\fIipsec auto \-\-up connname\fR. You will then be prompted for the username and password. To setup an XAUTH connection non\-interactively, which defeats the whole purpose of XAUTH, but is regularly requested by users, it is possible to use a whack command \-
\fIipsec whack \-\-name baduser \-\-ipsecgroup\-xauth \-\-xauthname badusername \-\-xauthpass password \-\-initiate\fR
The other side of the connection should be configured as
\fIrightxauthserver\fR. Acceptable values are
\fIyes\fR
or
\fIno\fR
(the default).
.TP
\fIleftxauthusername\fR
The XAUTH username associated with this XAUTH connection. The XAUTH password can be configured in the
\fIipsec.secrets\fR
file.
.TP
\fIleftmodecfgserver\fR
Left is a Mode Config server. It can push network configuration to the client. Acceptable values are
\fIyes\fR
or
\fIno\fR
(the default).
.TP
\fIleftmodecfgclient\fR
Left is a Mode Config client. It can receive network configuration from the server. Acceptable values are
\fIyes\fR
or
\fIno\fR
(the default).
.TP
\fImodecfgpull\fR
Pull the Mode Config network information from the server. Acceptable values are
\fIyes\fR
or
\fIno\fR
(the default).
.TP
\fImodecfgdns1\fR, \fImodecfgdns2\fR, \fImodecfgwins1\fR, \fImodecfgwins2\fR
Specify the IP address for DNS or WINS servers for the client to use.
.TP
\fIremote_peer_type\fR
Set the remote peer type. This can enable additional processing during the IKE negotiation. Acceptable values are
\fIcisco\fR
or
\fIietf\fR
(the default). When set to cisco, support for Cisco IPsec gateway redirection and Cisco obtained DNS and domainname are enabled. This includes automatically updating (and restoring) /etc/resolv.conf. These options require that XAUTH is also enabled on this connection.
.TP
\fIforceencaps\fR
In some cases, for example when ESP packets are filtered or when a broken IPsec peer does not properly recognise NAT, it can be useful to force RFC\-3948 encapsulation.
\fIforceencaps=yes\fR
forces the NAT detection code to lie and tell the remote peer that RFC\-3948 encapsulation (ESP in UDP port 4500 packets) is required. For this option to have any effect, the setup section option
\fInat_traversal=yes\fR
needs to be set. Acceptable values are
\fIyes\fR
or
\fIno\fR
(the default).
.TP
\fIoverlapip\fR
a boolean (yes/no) that determines, when *subnet=vhost: is used, if the virtual IP claimed by this states created from this connection can with states created from other connections.
.sp
Note that connection instances created by the Opportunistic Encryption or PKIX (x.509) instantiation system are distinct internally. They will inherit this policy bit.
.sp
The default is no.
.sp
This feature is only available with kernel drivers that support SAs to overlapping conns. At present only the (klips)mast protocol stack supports this feature.
.TP
\fIdpddelay\fR
Set the delay (in seconds) between Dead Peer Dectection (RFC 3706) keepalives (R_U_THERE, R_U_THERE_ACK) that are sent for this connection (default
30
seconds). If dpddelay is set, dpdtimeout also needs to be set.
.TP
\fIdpdtimeout\fR
Set the length of time (in seconds) we will idle without hearing either an R_U_THERE poll from our peer, or an R_U_THERE_ACK reply. After this period has elapsed with no response and no traffic, we will declare the peer dead, and remove the SA (default
120
seconds). If dpdtimeout is set, dpdaction also needs to be set.
.TP
\fIdpdaction\fR
When a DPD enabled peer is declared dead, what action should be taken.
\fIhold\fR
(default) means the eroute will be put into %hold status, while
\fIclear\fR
means the eroute and SA with both be cleared.
\fIrestart\fR
means the the SA will immediately be renegotiated, and
\fIrestart_by_peer\fR
means that
\fIALL\fR
SA's to the dead peer will renegotiated.
.sp
\fIdpdaction=clear\fR
is really only useful on the server of a Road Warrior config.
.TP
\fIpfs\fR
whether Perfect Forward Secrecy of keys is desired on the connection's keying channel (with PFS, penetration of the key\-exchange protocol does not compromise keys negotiated earlier); Since there is no reason to ever refuse PFS, Openswan will allow a connection defined with
\fIpfs=no\fR
to use PFS anyway. Acceptable values are
\fIyes\fR
(the default) and
\fIno\fR.
.TP
\fIpfsgroup\fR
This option is obsoleted, please use phase2alg if you need the pfs to be different from phase1 (the default) using: phase2alg=aes128\-md5;modp1024
.TP
\fIaggrmode\fR
Use Aggressive Mode instead of Main Mode. Aggressive Mode is less secure, and vulnerable to Denial Of Service attacks. It is also vulnerable to brute force attacks with software such as
\fIikecrack\fR. It should not be used, and it should especially not be used with XAUTH and group secrets (PSK). If the remote system administrator insists on staying irresponsible, enable this option.
.sp
Aggressive Mode is further limited to only one proposal \- there is no room for negotation. Therefor it is mandatory for Aggressive Mode connections that both
\fIike=\fR
and
\fIphase2alg=\fR
options are specified with exactly one fully specified proposal. Acceptable values are
\fIyes\fR
or
\fIno\fR
(the default).
.sp
The ISAKMP SA is created in exchange 1 in aggressive mode. Openswan has to send the exponent during that exchange, so it has to know what DH group to use before starting. This is why you can not have multiple DH groups in aggressive mode. It also has to pick which has to use since it needs to know which PRF to use to generate keys \- in IKEv1 the hash negotiated is really the PRF. In concept, Openswan could perhaps propose 3DES and AES128 in aggressive mode, but this needs to be verified and is currently not supported.
.TP
\fIsalifetime\fR
how long a particular instance of a connection (a set of encryption/authentication keys for user packets) should last, from successful negotiation to expiry; acceptable values are an integer optionally followed by
\fIs\fR
(a time in seconds) or a decimal number followed by
\fIm\fR,
\fIh\fR, or
\fId\fR
(a time in minutes, hours, or days respectively) (default
\fI8h\fR, maximum
\fI24h\fR). Normally, the connection is renegotiated (via the keying channel) before it expires. The two ends need not exactly agree on
\fIsalifetime\fR, although if they do not, there will be some clutter of superseded connections on the end which thinks the lifetime is longer.
.sp
The keywords "keylife" and "lifetime" are aliases for "salifetime."
.TP
\fIrekey\fR
whether a connection should be renegotiated when it is about to expire; acceptable values are
\fIyes\fR
(the default) and
\fIno\fR. The two ends need not agree, but while a value of
\fIno\fR
prevents Pluto from requesting renegotiation, it does not prevent responding to renegotiation requested from the other end, so
\fIno\fR
will be largely ineffective unless both ends agree on it.
.TP
\fIrekeymargin\fR
how long before connection expiry or keying\-channel expiry should attempts to negotiate a replacement begin; acceptable values as for
\fIsalifetime\fR
(default
\fI9m\fR). Relevant only locally, other end need not agree on it.
.TP
\fIrekeyfuzz\fR
maximum percentage by which
\fIrekeymargin\fR
should be randomly increased to randomize rekeying intervals (important for hosts with many connections); acceptable values are an integer, which may exceed 100, followed by a `%' (default set by
\fBipsec_pluto\fR(8), currently
\fI100%\fR). The value of
\fIrekeymargin\fR, after this random increase, must not exceed
\fIsalifetime\fR. The value
\fI0%\fR
will suppress time randomization. Relevant only locally, other end need not agree on it.
.TP
\fIkeyingtries\fR
how many attempts (a whole number or
\fI%forever\fR) should be made to negotiate a connection, or a replacement for one, before giving up (default
\fI%forever\fR). The value
\fI%forever\fR
means \(lqnever give up\(rq (obsolete: this can be written
0). Relevant only locally, other end need not agree on it.
.TP
\fIikelifetime\fR
how long the keying channel of a connection (buzzphrase: \(lqISAKMP SA\(rq) should last before being renegotiated; acceptable values as for
\fIkeylife\fR
(default set by
\fBipsec_pluto\fR(8), currently
\fI1h\fR, maximum
\fI24h\fR). The two\-ends\-disagree case is similar to that of
\fIkeylife\fR.
.TP
\fIcompress\fR
whether IPComp compression of content is proposed on the connection (link\-level compression does not work on encrypted data, so to be effective, compression must be done
\fIbefore\fR
encryption); acceptable values are
\fIyes\fR
and
\fIno\fR
(the default). The two ends need not agree. A value of
\fIyes\fR
causes IPsec to propose both compressed and uncompressed, and prefer compressed. A value of
\fIno\fR
prevents IPsec from proposing compression; a proposal to compress will still be accepted.
.TP
\fImetric\fR
Set the metric for the routes to the ipsecX or mastX interface. This makes it possible to do host failover from another interface to ipsec using route management. This value is passed to the _updown scripts as PLUTO_METRIC. This option is only available with KLIPS or MAST on Linux. Acceptable values are positive numbers, with the default being
\fI1\fR.
.TP
\fIdisablearrivalcheck\fR
whether KLIPS's normal tunnel\-exit check (that a packet emerging from a tunnel has plausible addresses in its header) should be disabled; acceptable values are
\fIyes\fR
and
\fIno\fR
(the default). Tunnel\-exit checks improve security and do not break any normal configuration. Relevant only locally, other end need not agree on it.
.TP
\fIfailureshunt\fR
what to do with packets when negotiation fails. The default is
\fInone\fR: no shunt;
\fIpassthrough\fR,
\fIdrop\fR, and
\fIreject\fR
have the obvious meanings.
.SS "CONN PARAMETERS:  MANUAL KEYING"
.PP
This command was obsoleted around the same time that Al Gore invented the internet. ipsec manual was used in the jurassic period to load static keys into the kernel. There are no rational reasons to use this, and it is not supported anymore. If you need to create static SAs, then you can use
\fIipsec spi\fR
and
\fIipsec eroute\fR
when using KLIPS or
\fIip xfrm \fR
or
\fIsetkey\fR
when using NETKEY.
.PP
No rational person uses static keys. They are not easier to use. REPEAT: they are not easier to use.
.SH "CONFIG SECTIONS"
.PP
At present, the only
\fIconfig\fR
section known to the IPsec software is the one named
\fIsetup\fR, which contains information used when the software is being started (see
\fBipsec_setup\fR(8)). Here's an example:
.sp
.nf

\fI
config setup
	interfaces="ipsec0=eth1 ipsec1=ppp0"
	klipsdebug=none
	plutodebug=control
	protostack=auto
	manualstart=
\fR
.fi
.sp
.PP
Parameters are optional unless marked \(lq(required)\(rq.
.PP
The currently\-accepted
\fIparameter\fR
names in a
\fIconfig\fR\fIsetup\fR
section are:
.TP
\fImyid\fR
the identity to be used for
\fI%myid\fR.
\fI%myid\fR
is used in the implicit policy group conns and can be used as an identity in explicit conns. If unspecified,
\fI%myid\fR
is set to the IP address in
\fI%defaultroute\fR
(if that is supported by a TXT record in its reverse domain), or otherwise the system's hostname (if that is supported by a TXT record in its forward domain), or otherwise it is undefined. An explicit value generally starts with ``\fI@\fR''.
.TP
\fIprotostack\fR
decide which protocol stack is going to be used. Valid values are "auto", "klips", "netkey" and "mast". The "mast" stack is a variation for the klips stack.
.TP
\fIinterfaces\fR
virtual and physical interfaces for IPsec to use: a single
\fIvirtual\fR\fI=\fR\fIphysical\fR
pair, a (quoted!) list of pairs separated by white space, or
\fI%none\fR. One of the pairs may be written as
\fI%defaultroute\fR, which means: find the interface
\fId\fR
that the default route points to, and then act as if the value was ``\fIipsec0=\fR\fId\fR''.
\fI%defaultroute\fR
is the default;
\fI%none\fR
must be used to denote no interfaces, or when using the NETKEY stack. If
\fI%defaultroute\fR
is used (implicitly or explicitly) information about the default route and its interface is noted for use by
\fBipsec_manual\fR(8)
and
\fBipsec_auto\fR(8).)
.TP
\fInat_traversal\fR
whether to accept/offer to support NAT (NAPT, also known as "IP Masqurade") workaround for IPsec. Acceptable values are:
\fIyes\fR
and
\fIno\fR
(the default). This parameter may eventually become per\-connection.
.TP
\fIdisable_port_floating\fR
whether to enable the newer NAT\-T standards for port floating. Acceptable values are
\fIno\fR
(the default) and
\fIyes\fR
.
.TP
\fIforce_keepalive\fR
whether to force sending NAT\-T keep\-alives to support NAT which are send to prevent the NAT router from closing its port when there is not enough traffic on the IPsec connection. Acceptable values are:
\fIyes\fR
and
\fIno\fR
(the default). This parameter may eventually become per\-connection.
.TP
\fIkeep_alive\fR
The delay (in seconds) for NAT\-T keep\-alive packets, if these are enabled using
\fIforce_keepalive\fR
This parameter may eventually become per\-connection.
.TP
\fIvirtual_private\fR
contains the networks that are allowed as subnet= for the remote client. In other words, the address ranges that may live behind a NAT router through which a client connects. This value is usually set to all the RFC\-1918 address space, excluding the space used in the local subnet behind the NAT (An IP address cannot live at two places at once). IPv4 address ranges are denoted as
\fI%v4:a.b.c.d/mm\fR
and IPv6 is denoted as
\fI%v6:aaaa::bbbb:cccc:dddd:eeee/mm\fR. One can exclude subnets by using the
\fI!\fR. For example, if the VPN server is giving access to 192.168.1.0/24, this option should be set to:
\fIvirtual_private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:!192.168.1.0/24\fR. This parameter is only needed on the server side and not on the client side that resides behind the NAT router, as the client will just use its IP address for the inner IP setting. This parameter may eventually become per\-connection.
.TP
\fIoe\fR
a boolean (yes/no) that determines if Opportunistic Encryption will be enabled. Opportunistic Encryption is the term to describe using IPsec tunnels without prearrangement. It uses IPSECKEY or TXT records to announce public RSA keys for certain IP's or identities.
.sp
For a complete description see /doc/draft\-richardson\-ipsec\-opportunistic.txt, doc/opportunism\-spec.txt and doc/opportunism.howto. See also the IETF BTNS working group and RFC4025.
.sp
The default is no.
.sp
This feature is only available with kernel drivers that support the caching of packets (%hold eroutes or equivalent) that allows us to respond to a packet from an unknown IP address. At present only the (klips)mast protocol stack supports this feature.
.TP
\fInhelpers\fR
how many
\fIpluto helpers\fR
are started to help with cryptographic operations. Pluto will start
\fI(n\-1)\fR
of them, where
\fIn\fR
is the number of CPU's you have (including hypherthreaded CPU's). A value of 0 forces pluto to do all operations in the main process. A value of \-1 tells pluto to perform the above calculation. Any other value forces the number to that amount.
.TP
\fIcrlcheckinterval\fR
interval, specified in seconds, after which pluto will verify loaded X.509 CRL's for expiration. If any of the CRL's is expired, or if they previously failed to get updated, a new attempt at updating the CRL is made. The first attempt to update a CRL is started at two times the crlcheckinterval. If set to
\fI0\fR, which is also the default value if this option is not specified, CRL updating is disabled.
.TP
\fIstrictcrlpolicy\fR
if not set, pluto is tolerant about missing or expired X.509 Certificate Revocation Lists (CRL's), and will allow peer certificates as long as they do not appear on an expired CRL. When this option is enabled, all connections with an expired or missing CRL will be denied. Active connections will be terminated at rekey time. This setup is more secure, but also dangerous. If the CRL is fetched through an IPsec tunnel with a CRL that expired, the entire VPN server will be dead in the water until a new CRL is manually transferred to the machine (if it allows non\-IPsec connections). Acceptable values are
\fIyes\fR
or
\fIno\fR
(the default).
.TP
\fIforwardcontrol\fR
This option is obsolete and ignored. Please use
\fInet.ipv4.ip_forward\ =\ 0\fR
in
\fI/etc/sysctl.conf\fR
instead to control the ip forwarding behaviour.
.TP
\fIrp_filter\fR
This option is obsolete and ignored. Please use the
\fInet.ipv4.conf/[iface]/rp_filter\ =\ 0\fR
options in
\fI/etc/sysctl.conf\fR
instead. This option is badly documented; it must be
0
in many cases for ipsec to function.
.TP
\fIsyslog\fR
the
\fBsyslog\fR(2)
\(lqfacility\(rq name and priority to use for startup/shutdown log messages, default
\fIdaemon.error\fR.
.TP
\fIklipsdebug\fR
how much KLIPS debugging output should be logged. An empty value, or the magic value
\fInone\fR, means no debugging output (the default). The magic value
\fIall\fR
means full output. Otherwise only the specified types of output (a quoted list, names separated by white space) are enabled; for details on available debugging types, see
\fBipsec_klipsdebug\fR(8). This KLIPS option has no effect on NETKEY, Windows or BSD stacks.
.TP
\fIplutodebug\fR
how much Pluto debugging output should be logged. An empty value, or the magic value
\fInone\fR, means no debugging output (the default). The magic value
\fIall\fR
means full output. Otherwise only the specified types of output (a quoted list, names without the
\fB\-\-debug\-\fR
prefix, separated by white space) are enabled; for details on available debugging types, see
\fBipsec_pluto\fR(8).
.TP
\fIuniqueids\fR
whether a particular participant ID should be kept unique, with any new (automatically keyed) connection using an ID from a different IP address deemed to replace all old ones using that ID. Acceptable values are
\fIyes\fR
(the default) and
\fIno\fR. Participant IDs normally
\fIare\fR
unique, so a new (automatically\-keyed) connection using the same ID is almost invariably intended to replace an old one.
.TP
\fIplutorestartoncrash\fR
prevent pluto from restarting after it crashed. This option should only be used when debugging a crasher. It will prevent overwriting a core file on a new start, or a cascade of core files. This option is also required if used with plutostderrlog= to avoid clearing the logs of the crasher. Values can be yes (the default) or no.
.TP
\fIplutoopts\fR
additional options to pass to pluto upon startup. See
\fBipsec_pluto\fR(8).
.TP
\fIplutostderrlog\fR
do not use syslog, but rather log to stderr, and direct stderr to the argument file.
.TP
\fIpluto\fR
whether to start Pluto or not; Values are
\fIyes\fR
(the default) or
\fIno\fR
(useful only in special circumstances).
.TP
\fIplutowait\fR
should Pluto wait for each negotiation attempt that is part of startup to finish before proceeding with the next? Values are
\fIyes\fR
or
\fIno\fR
(the default).
.TP
\fIprepluto\fR
shell command to run before starting Pluto (e.g., to decrypt an encrypted copy of the
\fIipsec.secrets\fR
file). It's run in a very simple way; complexities like I/O redirection are best hidden within a script. Any output is redirected for logging, so running interactive commands is difficult unless they use
\fI/dev/tty\fR
or equivalent for their interaction. Default is none.
.TP
\fIpostpluto\fR
shell command to run after starting Pluto (e.g., to remove a decrypted copy of the
\fIipsec.secrets\fR
file). It's run in a very simple way; complexities like I/O redirection are best hidden within a script. Any output is redirected for logging, so running interactive commands is difficult unless they use
\fI/dev/tty\fR
or equivalent for their interaction. Default is none.
.TP
\fIdumpdir\fR
in what directory should things started by
\fIsetup\fR
(notably the Pluto daemon) be allowed to dump core? The empty value (the default) means they are not allowed to.
.TP
\fIfragicmp\fR
whether a tunnel's need to fragment a packet should be reported back with an ICMP message, in an attempt to make the sender lower his PMTU estimate; acceptable values are
\fIyes\fR
(the default) and
\fIno\fR. This KLIPS option has no effect on NETKEY, Windows or BSD stacks.
.TP
\fIhidetos\fR
whether a tunnel packet's TOS field should be set to
0
rather than copied from the user packet inside; acceptable values are
\fIyes\fR
(the default) and
\fIno\fR. This KLIPS option has no effect on NETKEY, Windows or BSD stacks.
.TP
\fIoverridemtu\fR
value that the MTU of the ipsec\fIn\fR
interface(s) should be set to, overriding IPsec's (large) default. This parameter is needed only in special situations. This KLIPS option has no effect on NETKEY, Windows or BSD stacks.
.SH "IMPLICIT CONNS"
.PP
The system automatically defines several conns to implement default policy groups. Each can be overridden by explicitly defining a new conn with the same name. If the new conn has
\fIauto=ignore\fR, the definition is suppressed.
.PP
Here are the automatically supplied definitions.
.sp
.nf

\fI
conn clear
	type=passthrough
	authby=never
	left=%defaultroute
	right=%group
	auto=route

conn clear\-or\-private
	type=passthrough
	left=%defaultroute
	leftid=%myid
	right=%opportunisticgroup
	failureshunt=passthrough
	keyingtries=3
	ikelifetime=1h
	salifetime=1h
	rekey=no
	auto=route

conn private\-or\-clear
	type=tunnel
	left=%defaultroute
	leftid=%myid
	right=%opportunisticgroup
	failureshunt=passthrough
	keyingtries=3
	ikelifetime=1h
	salifetime=1h
	rekey=no
	auto=route

conn private
	type=tunnel
	left=%defaultroute
	leftid=%myid
	right=%opportunisticgroup
	failureshunt=drop
	keyingtries=3
	ikelifetime=1h
	salifetime=1h
	rekey=no
	auto=route

conn block
	type=reject
	authby=never
	left=%defaultroute
	right=%group
	auto=route

# default policy
conn packetdefault
	type=tunnel
	left=%defaultroute
	leftid=%myid
	left=0.0.0.0/0
	right=%opportunistic
	failureshunt=passthrough
	keyingtries=3
	ikelifetime=1h
	salifetime=1h
	rekey=no
	auto=route
\fR
.fi
.sp
.PP
These conns are
\fInot\fR
affected by anything in
\fIconn %default\fR. They will only work if
\fI%defaultroute\fR
works. The
\fIleftid\fR
will be the interfaces IP address; this requires that reverse DNS records be set up properly.
.PP
The implicit conns are defined after all others. It is appropriate and reasonable to use
\fIalso=private\-or\-clear\fR
(for example) in any other opportunistic conn.
.SH "POLICY GROUP FILES"
.PP
The optional files under
\fI/etc/ipsec.d/policy\fR, including
.sp
.nf

/etc/ipsec.d/policies/clear
/etc/ipsec.d/policies/clear\-or\-private
/etc/ipsec.d/policies/private\-or\-clear
/etc/ipsec.d/policies/private
/etc/ipsec.d/policies/block

.fi
.sp
.PP
may contain policy group configuration information to supplement
\fIipsec.conf\fR. Their contents are not security\-sensitive.
.PP
These files are text files. Each consists of a list of CIDR blocks, one per line. White space followed by # followed by anything to the end of the line is a comment and is ignored, as are empty lines.
.PP
A connection in
\fIipsec.conf\fR
which has
\fIright=%group\fR
or
\fIright=%opportunisticgroup\fR
is a policy group connection. When a policy group file of the same name is loaded, with
.PP
\ \ \ \ \ \fIipsec auto \-\-rereadgroups\fR
.PP
or at system start, the connection is instantiated such that each CIDR block serves as an instance's
\fIright\fR
value. The system treats the resulting instances as normal connections.
.PP
For example, given a suitable connection definition
\fIprivate\fR, and the file
\fI/etc/ipsec.d/policy/private\fR
with an entry 192.0.2.3, the system creates a connection instance
\fIprivate#192.0.2.3.\fR
This connection inherits all details from
\fIprivate\fR, except that its right client is 192.0.2.3.
.SH "DEFAULT POLICY GROUPS"
.PP
The standard Openswan install includes several policy groups which provide a way of classifying possible peers into IPsec security classes:
\fIprivate\fR
(talk encrypted only),
\fIprivate\-or\-clear\fR
(prefer encryption),
\fIclear\-or\-private\fR
(respond to requests for encryption),
\fIclear\fR
and
\fIblock\fR. Implicit policy groups apply to the local host only, and are implemented by the
\fIIMPLICIT CONNECTIONS\fR
described above.
.SH "CHOOSING A CONNECTION [THIS SECTION IS EXTREMELY OUT OF DATE"
.PP
When choosing a connection to apply to an outbound packet caught with a
\fI%trap,\fR
the system prefers the one with the most specific eroute that includes the packet's source and destination IP addresses. Source subnets are examined before destination subnets. For initiating, only routed connections are considered. For responding, unrouted but added connections are considered.
.PP
When choosing a connection to use to respond to a negotiation which doesn't match an ordinary conn, an opportunistic connection may be instantiated. Eventually, its instance will be /32 \-> /32, but for earlier stages of the negotiation, there will not be enough information about the client subnets to complete the instantiation.
.SH "FILES"
.sp
.nf
/etc/ipsec.conf
/etc/ipsec.d/policies/clear
/etc/ipsec.d/policies/clear\-or\-private
/etc/ipsec.d/policies/private\-or\-clear
/etc/ipsec.d/policies/private
/etc/ipsec.d/policies/block
.fi
.sp
.SH "SEE ALSO"
.PP
\fBipsec\fR(8),
\fBipsec_ttoaddr\fR(8),
\fBipsec_auto\fR(8),
\fBipsec_manual\fR(8),
\fBipsec_rsasigkey\fR(8)
.SH "HISTORY"
.PP
Designed for the FreeS/WAN project <[1]\&\fIhttp://www.freeswan.org\fR> by Henry Spencer.
.SH "BUGS"
.PP
Before reporting new bugs, please ensure you are using the latest version of Openswan, and if not using KLIPS, please ensure you are using the latest kernel code for your IPsec stack.
.PP
When
\fItype\fR
or
\fIfailureshunt\fR
is set to
\fIdrop\fR
or
\fIreject,\fR
Openswan blocks outbound packets using eroutes, but assumes inbound blocking is handled by the firewall. Openswan offers firewall hooks via an \(lqupdown\(rq script. However, the default
\fIipsec _updown\fR
provides no help in controlling a modern firewall.
.PP
Including attributes of the keying channel (authentication methods,
\fIikelifetime\fR, etc.) as an attribute of a connection, rather than of a participant pair, is dubious and incurs limitations.
.PP
The use of
\fI%any\fR
with the
\fIprotoport=\fR
option is ambiguous. Should the SA permits any port through or should the SA negotiate any single port through? The first is a basic conn with a wildcard. The second is a template. The second is the current behaviour, and it's wrong for quite a number of uses involving TCP. The keyword
\fI%one\fR
may be introduced in the future to seperate these two cases.
.PP
\fIipsec_manual\fR
is not nearly as generous about the syntax of subnets, addresses, etc. as the usual Openswan user interfaces. Four\-component dotted\-decimal must be used for all addresses. It
\fIis\fR
smart enough to translate bit\-count netmasks to dotted\-decimal form.
.PP
It would be good to have a line\-continuation syntax, especially for the very long lines involved in RSA signature keys.
.PP
\fIFirst packet caching\fR
is only implemented for the KLIPS(NG) and MAST stacks. NETKEY returns POSIX\-breaking responses, visiable as
\fIconnect: Resource temporarily unavailable\fR
errors. This affects Opportunistic Encryption and DPD. Functionality on the BSD and Windows stacks is unknown.
.PP
Some state information is only available when using KLIPS, and will return errors on other IPsec stacks. These include
\fIipsec eroute\fR,
\fIipsec spi\fR
and
\fIipsec look\fR.
.PP
Multiple L2TP clients behind the same NAT router, and multiple L2TP clients behind different NAT routers using the same Virtual IP is currently only working for the KLIPSNG stack.
.PP
The ability to specify different identities,
\fIauthby\fR, and public keys for different automatic\-keyed connections between the same participants is misleading; this doesn't work dependably because the identity of the participants is not known early enough. This is especially awkward for the \(lqRoad Warrior\(rq case, where the remote IP address is specified as
0.0.0.0, and that is considered to be the \(lqparticipant\(rq for such connections.
.PP
In principle it might be necessary to control MTU on an interface\-by\-interface basis, rather than with the single global override that
\fIoverridemtu\fR
provides. This feature is planned for a future release.
.PP
A number of features which
\fIcould\fR
be implemented in both manual and automatic keying actually are not yet implemented for manual keying. This is unlikely to be fixed any time soon.
.PP
If conns are to be added before DNS is available,
\fIleft=\fR\fIFQDN\fR,
\fIleftnextop=\fR\fIFQDN\fR, and
\fIleftrsasigkey=%dnsonload\fR
will fail.
\fBipsec_pluto\fR(8)
does not actually use the public key for our side of a conn but it isn't generally known at a add\-time which side is ours (Road Warrior and Opportunistic conns are currently exceptions).
.PP
The
\fImyid\fR
option does not affect explicit
\fI ipsec auto \-\-add\fR
or
\fIipsec auto \-\-replace\fR
commands for implicit conns.
.SH "REFERENCES"
.TP 3
1.\ http://www.freeswan.org
\%http://www.freeswan.org
