'\" t
.\"     Title: IPSEC_LIVETEST
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 10/06/2010
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "IPSEC_LIVETEST" "8" "10/06/2010" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ipsec_livetest \- see if Openswan has been installed correctly, interacting with a test target
.SH "SYNOPSIS"
.HP \w'\fBipsec\fR\ 'u
\fBipsec\fR \fIlivetest\fR [\-\-force]
.SH "DESCRIPTION"
.PP
Invoked without argument,
\fIlivetest\fR
attempts to connect to livetest\&.xelerance\&.com in multiple secure fashions\&. It first attempts ping, then ikeping on udp port 500, ikeping on udp port 4500, then configures a connection using a random ID, using a a custom HTTP\-based protocol\&.
.SH "FILES"
.sp
.if n \{\
.RS 4
.\}
.nf
/proc/net/ipsec_eroute
/etc/ipsec\&.secrets
.fi
.if n \{\
.RE
.\}
.SH "HISTORY"
.PP
Written for the Openswan project <\m[blue]\fBhttp://www\&.openswan\&.org\fR\m[]> by Daniel Snider as part of the Google Summer of Code 2009
.SH "BUGS"
.PP
This functionality is still experimental
