.\"     Title: IPSEC_LIVETEST
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/14/2008
.\"    Manual: 13 July 2004
.\"    Source: 13 July 2004
.\"
.TH "IPSEC_LIVETEST" "8" "11/14/2008" "13 July 2004" "13 July 2004"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ipsec_livetest - see if Openswan has been installed correctly, interacting with a test target
.SH "SYNOPSIS"
.HP 6
\fBipsec\fR \fIlivetest\fR [\-\-force]
.SH "DESCRIPTION"
.PP
Invoked without argument,
\fIlivetest\fR
attempts to connect to livetest\.xelerance\.com in multiple secure fashions\. It first attempts ping, then ikeping on udp port 500, ikeping on udp port 4500, then configures a connection using a random ID, using a a custom HTTP\-based protocol\.
.SH "FILES"
.sp
.RS 4
.nf
/proc/net/ipsec_eroute
/etc/ipsec\.secrets
.fi
.RE
.sp
.SH "HISTORY"
.PP
Written by Xelerance Corporation for the Openswan project <\fIhttp://www\.openswan\.org\fR> by Paul Wouters\.
.SH "BUGS"
.PP
This functionality is a work in process, and not yet functional\.
