# Makefile for miscelaneous programs
# Copyright (C) 2004  Michael Richardson	<mcr@xelerance.com>
# 
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.  See <http://www.fsf.org/copyleft/gpl.txt>.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# RCSID $Id: Makefile,v 1.1.2.1 2004/07/15 03:54:13 paul Exp $

OPENSWANSRCDIR=../..
include ${OPENSWANSRCDIR}/Makefile.inc

PROGRAM=livetest

include ../Makefile.program

#
# $Log: Makefile,v $
# Revision 1.1.2.1  2004/07/15 03:54:13  paul
# added livetest clientsite test.
#
# Revision 1.1  2004/07/13 22:31:38  mcr
#    live test template
#
#
#

