# -*- makefile -*-
TESTNAME=xf13-parentI3

SAMPLEDIR=../../libpluto/samples
CONNNAME=parker1--jj2
ENDNAME=parker
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}

EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_crypto.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_rsa.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_psk.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/kernel.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/kernel_forces.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/signatures.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/keymgmt.o


# /dev/null is output pcap, as there is none.
UNITTEST1ARGS=-r ${WHACKFILE} ${CONNNAME} /dev/null parentR1.pcap cryptoR2.pcap

pcapupdate:
	cp ../../libpluto/lp08-parentR1/OUTPUT/parentR1.pcap     parentR1.pcap
	cp ../../ikev2crypto/ct12-parentR2/OUTPUT/cryptoR2.pcap  cryptoR2.pcap




