#!/bin/sh
# $Id: check-psk-crack-1,v 1.1.1.1 2005/01/13 18:44:53 mcr Exp $
#
# check-psk-crack-1 -- Shell script to test psk-crack --help and --version
#
# Author: Roy Hills
# Date: 19 November 2004
#
# This shell script checks that "psk-crack --help" and "psk-crack --version"
# work.  These options don't use much of the psk-scan functionallity, so if
# they fail, then there is a fundimental problem with the program.
#
TMPFILE=/tmp/ike-scan-test.$$.tmp
#
echo "Checking psk-crack --help ..."
$srcdir/psk-crack --help 2> $TMPFILE
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED"
   exit 1
fi
grep '^See the ike-scan homepage at ' $TMPFILE >/dev/null
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED"
   exit 1
fi
echo "ok"
#
echo "Checking psk-crack --version ..."
$srcdir/psk-crack --version 2> $TMPFILE
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED"
   exit 1
fi
grep '^ike-scan comes with NO WARRANTY ' $TMPFILE >/dev/null
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED"
   exit 1
fi
echo "ok"
#
rm -f $TMPFILE
