.\"     Title: _PLUTORUN
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/14/2008
.\"    Manual: 25 Apr 2002
.\"    Source: 25 Apr 2002
.\"
.TH "IPSEC_PLUTORUN" "8" "11/14/2008" "25 Apr 2002" "25 Apr 2002"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ipsec_plutorun \- internal script to start pluto
.SH "DESCRIPTION"
.PP
\fI_plutorun\fR
is called by
\fB_realsetup\fR
to configure and bring up
\fBipsec_pluto(8)\.\fR
It calls
\fB_plutoload\fR
to invoke pluto, and watches to makes sure that pluto is restarted if it fails\.
.SH "SEE ALSO"
.PP
\fBipsec\fR(8),
\fBipsec_setup\fR(8),
\fBipsec__realsetup\fR(8),
\fBipsec__plutoload\fR(8),
\fBipsec_pluto\fR(8)\.
.SH "HISTORY"
.PP
Man page written for the Linux FreeS/WAN project <\fIhttp://www\.freeswan\.org/\fR> by Michael Richardson\. Original program written by Henry Spencer\.
