.\"     Title: IPSEC_SHOWDEFAULTS
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/14/2008
.\"    Manual: 23 Jan 2000
.\"    Source: 23 Jan 2000
.\"
.TH "IPSEC_SHOWDEFAULTS" "8" "11/14/2008" "23 Jan 2000" "23 Jan 2000"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ipsec showdefaults - show %defaultroute defaults
.SH "SYNOPSIS"
.HP 6
\fBipsec\fR \fIshowdefaults\fR
.SH "DESCRIPTION"
.PP
\fIShowdefaults\fR
outputs (on standard output) a terse description of the defaults used by the
\fB%defaultroute\fR
facilities in
\fBipsec_auto\fR(8)
and
\fBipsec_manual\fR(8)\.
.PP
Beware that the exact output format is subject to change\.
.SH "DIAGNOSTICS"
.PP
Normal exit status is 0\. If no defaults are available, i\.e\. the
\fBinterfaces\fR
parameter in
\fBconfig setup\fR
is not
\fB%defaultroute\fR, produces a message on standard error and exits with status 1\.
.SH "FILES"
.PP
/var/run/pluto/ipsec\.info
.SH "HISTORY"
.PP
Written for the Linux FreeS/WAN project <\fIhttp://www\.freeswan\.org\fR> by Henry Spencer\.
