#!/bin/sh

#53         192.139.46.6/32    -> 192.139.46.20/32   => %hold

ipsec eroute | grep '%hold' | while read usage src arrow dst arr2 type
do
	echo Fixing $dst
	ipsec eroute --del --eraf inet --src $src --dst $dst
	ipsec eroute --replace --eraf inet --src $src --dst $dst --said %pass
done


