.TH "CISCO-DECRYPT" "1" "August 2007" "cisco-decrypt" "vpnc"
.SH "NAME"
cisco-decrypt \- decrypts an obfuscated Cisco vpn client pre-shared key
.\"
.\" $Id: cisco-decrypt.1 204 2007-08-14 18:01:28Z Joerg Mayer $
.\"
.SH "SYNOPSIS"
.B cisco-decrypt
\fI<obfuscated pre-shared key>
.SH "DESCRIPTION"
This command accompanies \fBvpnc\fR. It decrypts the obfuscated
pre-shared key from *.pcf\-configuration files, which must be
specified on the command line.

The result will be printed to STDOUT.
.SH "AUTHOR"
cisco-decrypt was originally written by Maurice Massar. This man\-page was
written by Jörg Mayer, based on the pcf2vpnc manpage written by Wolfram Sang
(ninja(at)the\-dreams.de).

Permission is granted to copy, distribute and/or modify this document under
the terms of the GNU General Public License, Version 2 any 
later version published by the Free Software Foundation.
.PP 
On Debian systems, the complete text of the GNU General Public
License can be found in /usr/share/common\-licenses/GPL.
.SH "SEE ALSO"
.BR vpnc(8)
.BR pcf2vpnc(1)
