# -*- makefile -*-
ENDNAME=jamesjohnson
CONNNAME=parker
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME} parentI1badKE.pcap OUTPUT/parentI1badKE.pcap
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}

TESTNAME=parentR1any

pcapupdate:
	cp ../lp02-parentI1/OUTPUT/parentI1.pcap parentI1.pcap
