#!/bin/sh

# this explicitely builds with LIBNSS into a different OBJDIR.
# it used by tests/build/b02-libnss/, but also by developers to
# validate libnss builds.

if [ -z "${DESTDIR}" ]; then
   DESTDIR=`pwd`/OBJ.libnss.${BUILDENV}.${ARCH}/root
   mkdir -p $DESTDIR
fi

${MAKE-make} --no-print-directory USE_LIBNSS=true DESTDIR=${DESTDIR} USE_LIBNSS=true programs install

