# -*- makefile -*-
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}
CONNNAME=cpenohint
UNITTESTARGS=-r ${WHACKFILE} ${CONNNAME}

TESTNAME=dnscpeI1
ENDNAME=dnsdelayclient
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/dnskey.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/adns.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/pending.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/initiate.o
EXTRALIBS+=-lresolv


pcapupdate:
	@true
