include ../lp15-respondself/Makefile

PCAPDEPENDENCIES = ../lp61-nattI1/OUTPUT/nattI1.pcap
include ../Makefile.pcapupdate

pcapupdate: ${PCAPDEPENDENCIES}
	cp ../lp61-nattI1/OUTPUT/nattI1.pcap nattI1.pcap


# Local Variables:
# gdb-command: ""
# End Variables:
#
