#!/bin/sh
# $Id: check-run3,v 1.1.1.1 2005/01/13 18:44:53 mcr Exp $
#
# check-run2 -- Shell script to test ike-scan's lists
#
# Author: Roy Hills
# Date: 13 January 2004
#
# This shell script runs ike-scan with the highest verbose level to display
# the contents of the internal lists: the host list, the backoff list, and
# the vendor id patterns list.  It then checks that all of these lists are
# displayed.
#
TMPFILE=/tmp/ike-scan-test.$$.tmp
#
echo "Checking ike-scan internal lists ..."
$srcdir/ike-scan --nodns --sport=0 --dport=33434 -v -v -v --showbackoff \
   --retry=1 --patterns=$srcdir/ike-backoff-patterns \
   --vidpatterns=$srcdir/ike-vendor-ids 127.0.0.1 >$TMPFILE 2>&1
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED - ike-scan returned non-zero exit code"
   exit 1
fi
grep '^Total of [0-9]* host entries\.$' $TMPFILE >/dev/null
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED - host list summary not found"
   exit 1
fi
grep '^Total of [0-9]* backoff pattern entries\.$' $TMPFILE >/dev/null
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED - backoff list summary not found"
   exit 1
fi
grep '^Total of [0-9]* Vendor ID pattern entries\.$' $TMPFILE >/dev/null
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED - vendor id list summary not found"
   exit 1
fi
echo "ok"
#
rm -f $TMPFILE
