#!/bin/sh
# $Id: check-run1,v 1.1.1.1 2005/01/13 18:44:53 mcr Exp $
#
# check-run1 -- Shell script to test ike-scan --help and --version
#
# Author: Roy Hills
# Date: 12 January 2004
#
# This shell script checks that "ike-scan --help" and "ike-scan --version"
# work.  These options don't use much of the ike-scan functionallity, so if
# they fail, then there is a fundimental problem with the program.
#
TMPFILE=/tmp/ike-scan-test.$$.tmp
#
echo "Checking ike-scan --help ..."
$srcdir/ike-scan --help 2> $TMPFILE
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED"
   exit 1
fi
grep '^See the ike-scan homepage at ' $TMPFILE >/dev/null
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED"
   exit 1
fi
echo "ok"
#
echo "Checking ike-scan --version ..."
$srcdir/ike-scan --version 2> $TMPFILE
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED"
   exit 1
fi
grep '^ike-scan comes with NO WARRANTY ' $TMPFILE >/dev/null
if test $? -ne 0; then
   rm -f $TMPFILE
   echo "FAILED"
   exit 1
fi
echo "ok"
#
rm -f $TMPFILE
