# -*- makefile -*-
TESTNAME=parentI3
CONNNAME=parker1--jj2
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}
UNITTEST1ARGS=-r ${WHACKFILE} ${CONNNAME} /dev/null ../lp10-parentI2/parentR1.pcap parentR2.pcap
ENDNAME=parker

pcapupdate:
	cp ../lp12-parentR2/OUTPUT/parentR2.pcap parentR2.pcap


