include ../lp15-respondself/Makefile

pcapupdate:
	cp ../lp36-h2hI1/OUTPUT/h2hI1.pcap h2hI1-noikev2.pcap


# Local Variables:
# compile-command: "make clean && make check"
# gdb-command: ""
# End Variables:
#
