EXTRAFLAGS+=-I../../libpluto -I../../libpluto/lp123-peerA-I2
include ../../libpluto/lp10-parentI2/Makefile
EXTRAFLAGS+=-DSAMPLEDIR=\"${SAMPLEDIR}\"

# Local Variables:
# gdb-command: ""
# End Variables:
#
