SAMPLEDIR=../../libpluto/samples
TESTNAME=cryptoI2
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}
CONNNAME=parker1--jj2
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME} parentR1.pcap OUTPUT/${TESTNAME}.pcap
ENDNAME=parker


