#!/bin/sh

# $1 is READWRITE
# $2 is NAME
# $3 is CONFIG
# REFERENCE stdout is in ${NAME}.out, raw is OUTPUT/${NAME}.raw
# REFERENCE stderr is in ${NAME}.err, raw is OUTPUT/${NAME}.err

READWRITE=$1
NAME=$2
CONFIG=$3
REFOUT=${NAME}.out
REFERR=${NAME}.err
TEEOUT=OUTPUT/${REFOUT}
TEEERR=OUTPUT/${REFERR}

set -e
${READWRITE} --config ${CONFIG} 2>${TEEERR} | tee ${TEEOUT} | diff - ${REFOUT}
diff ${TEEERR} ${REFERR}
