# -*- makefile -*-
# -*- makefile -*-
CONNNAME=home
ENDNAME=davecert-id
PCAPOUTPUT=davecertI2-id.pcap
UNITTEST1ARGS=-r ${WHACKFILE} ${CONNNAME} davecert-R1-id.pcap  OUTPUT/${PCAPOUTPUT}

TESTNAME=davecertI2-id

PCAPDEPENDENCIES = ../lp53-davecert-gatewayID-R1/OUTPUT/davecert-R1-id.pcap
include ../Makefile.pcapupdate

pcapupdate: ${PCAPDEPENDENCIES}
	cp ../lp53-davecert-gatewayID-R1/OUTPUT/davecert-R1-id.pcap .




