# Makefile for simpleca programs
# Copyright (C) 2004	Michael Richardson <mcr@xelerance.com>
# 
# This program has a GPL compatible license.
#
# RCSID $Id: Makefile,v 1.1 2004/06/17 02:03:27 mcr Exp $

OPENSWANSRCDIR=../..
include ${OPENSWANSRCDIR}/Makefile.inc

PROGRAM=simpleca
EXTRA5PROC=${PROGRAM}.5

include ../Makefile.program

#
# $Log: Makefile,v $
# Revision 1.1  2004/06/17 02:03:27  mcr
#    makefile for simpleca (not yet committed itself)
#
#
#
