#!/bin/sh

# This script expects the following variables to be in the environment:
# DESTDIR
# OPENSWANSRCDIR
# ARCH
# IPSECVERSION

# set -x

cd $DESTDIR 
rm -f *.tar.gz 

mkdir -p $OPENSWANSRCDIR/packaging/ipkg/ipkg
cp $OPENSWANSRCDIR/packaging/ipkg/debian-binary . 
cp $OPENSWANSRCDIR/packaging/ipkg/conffiles . 

cat $OPENSWANSRCDIR/packaging/ipkg/control-openswan.dist | sed s/VERSION/$IPSECVERSION/ |sed s/ARCH/$ARCH/ > $OPENSWANSRCDIR/packaging/ipkg/control-openswan 

cp $OPENSWANSRCDIR/packaging/ipkg/control-openswan control 

tar -czf ./control.tar.gz ./conffiles ./control  

tar -czf ./data.tar.gz ./* --exclude=control.tar.gz --exclude=conffiles --exclude=control --exclude=debian-binary 

tar -czf $OPENSWANSRCDIR/packaging/ipkg/ipkg/openswan-utils-$IPSECVERSION.$ARCH.ipk ./debian-binary ./control.tar.gz ./data.tar.gz  
mkdir -p $OPENSWANSRCDIR/packaging/ipkg/kernel-module 
cd $OPENSWANSRCDIR/packaging/ipkg/kernel-module 

rm -f *.tar.gz 
cp $OPENSWANSRCDIR/packaging/ipkg/debian-binary . 

cat $OPENSWANSRCDIR/packaging/ipkg/control-openswan-module.dist | sed s/VERSION/$IPSECVERSION/ |sed s/ARCH/$ARCH/ > $OPENSWANSRCDIR/packaging/ipkg/control-openswan-module 

cp $OPENSWANSRCDIR/packaging/ipkg/control-openswan-module control 

tar czf ./control.tar.gz ./control  

tar czf ./data.tar.gz * --exclude=control.tar.gz --exclude=control --exclude=debian-binary 

tar czf $OPENSWANSRCDIR/packaging/ipkg/ipkg/openswan-module-$IPSECVERSION.$ARCH.ipk ./debian-binary ./control.tar.gz ./data.tar.gz  
rm -rf $OPENSWANSRCDIR/packaging/ipkg/ipkg/binaries/* 
rm -rf $OPENSWANSRCDIR/packaging/ipkg/ipkg/kernel-module/*
