# -*- makefile -*-
ALG:=aes
CONFIG_YES:=$(CONFIG_IKE_ALG_AES)

ALG_SRCS-$(CONFIG_YES)  := $(ALG_SRCS-$(CONFIG_YES)) ike_alg_$(ALG).c
ALG_OBJS-$(CONFIG_YES)  := $(ALG_OBJS-$(CONFIG_YES)) ike_alg_$(ALG).o

ike_alg_$(ALG).o: ike_alg_$(ALG).c
	@echo CC $(notdir $<)
	@$(CC) $(COPTS) $(ALLFLAGS) -c $<
