# -*- makefile -*-
TESTNAME=respondselfR2
CONNNAME=gateway--any
UNITTEST1PCAP=OUTPUT/parentR2_allzero.pcap
UNITTEST2PCAP=OUTPUT/parentR2.pcap
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME} parentI1.pcap parentI2_allzero.pcap ${UNITTEST1PCAP}
UNITTEST2ARGS=${WHACKFILE} ${CONNNAME} parentI1.pcap parentI2.pcap ${UNITTEST2PCAP}
ENDNAME=rw
