TESTNAME=respondselfR2
CONNNAME=gateway--any
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME} parentI1.pcap parentI2_allzero.pcap OUTPUT/parentR2_allzero.pcap
UNITTEST2ARGS=${WHACKFILE} ${CONNNAME} parentI1.pcap parentI2.pcap OUTPUT/parentR2.pcap
ENDNAME=rw
