.\"     Title: IPSEC_SECRETS
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/14/2008
.\"    Manual: 31 Aug 2003
.\"    Source: 31 Aug 2003
.\"
.TH "IPSEC_SECRETS" "8" "11/14/2008" "31 Aug 2003" "31 Aug 2003"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ipsec secrets - prompt for PIN codes and passphrases
.SH "SYNOPSIS"
.HP 6
\fBipsec\fR \fIsecrets\fR
.SH "DESCRIPTION"
.PP
\fISecrets\fR
is an alias for
\fBipsec auto \-\-rereadsecrets\fR
and rereads all the secrets in the
\fIipsec\.secrets\fR
file\. The user will be prompted for all private RSA keys protected by PIN codes and passphrases\.
.SH "SEE ALSO"
.PP
ipsec\.\fBsecrets\fR(5)
.SH "HISTORY"
.PP
Written for Openswan <http://www\.openswan\.org> by Andreas Steffen\.
.SH "BUGS"
.PP
None
