# -*- makefile -*-
TESTNAME=certreplydaveR1
CONNNAME1=rw-any
CONNNAME=${CONNNAME1} rw-carol rw-dave
UNITTEST1PCAP=OUTPUT/${TESTNAME}.pcap
LP24=../lp24-certreplydaveR2
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME1} ${UNITTEST1PCAP} carolI1.pcap carolI2.pcap davecertI1.pcap
ENDNAME=gatewaycert
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/x509keys.o

# no updates because all packets come from LP24
pcapupdate:
	cp ../lp18-certificateselfI1/OUTPUT/certificateselfI1.pcap  carolI1.pcap
	cp ../lp20-certificateselfI2/OUTPUT/certificateselfI2.pcap  carolI2.pcap
	cp ../lp23-davecertI1/OUTPUT/davecertI1.pcap                davecertI1.pcap

# Local Variables:
# gdb-command: ""
# End Variables:
#

