# -*- makefile -*-

EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/x509keys.o
CONNNAME=home
TESTNAME=certificateselfI2
PCAPOUTPUT=${TESTNAME}.pcap
UNITTEST1ARGS=-r ${WHACKFILE} ${CONNNAME} OUTPUT/${PCAPOUTPUT} parentR1.pcap
ENDNAME=rwcert

SANITYARGS=-f leakfix.sed

PCAPDEPENDENCIES = ../lp19-certreplyselfR1/OUTPUT/certreplyselfR1.pcap
include ../Makefile.pcapupdate

pcapupdate: ${PCAPDEPENDENCIES}
	cp ../lp19-certreplyselfR1/OUTPUT/certreplyselfR1.pcap parentR1.pcap

