# -*- makefile -*-

EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/x509keys.o
CONNNAME=home
PCAPOUTPUT=parentI2.pcap
UNITTEST1ARGS=-r ${WHACKFILE} ${CONNNAME} parentR1.pcap      OUTPUT/parentI2.pcap
ENDNAME=rwcert

TESTNAME=certificateselfI2
SANITYARGS=-f leakfix.sed

pcapupdate:
	cp ../lp19-certreplyselfR1/OUTPUT/certreplyselfR1.pcap parentR1.pcap

