#!/bin/sh

openssl ca -ss_cert cacert.pem -config ./openssl.cnf -days 3650 -keyfile cakey.pem -out newcacert.pem

if [ -s newcacert.pem ]
then
	mv cacert.pem cacert-expired.pem
	mv newcacert.pem cacert.pem
fi



