# -*- makefile -*-
TESTNAME=nattI3

CONNNAME=parker1--jj2
ENDNAME=parker
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}

# /dev/null is output pcap.
UNITTEST1ARGS=-r ${WHACKFILE} ${CONNNAME} /dev/null nattR1.pcap nattR2.pcap

PCAPDEPENDENCIES = ../lp62-nattR1/OUTPUT/nattR1.pcap ../lp64-nattR2/OUTPUT/nattR2.pcap
include ../Makefile.pcapupdate

pcapupdate: ${PCAPDEPENDENCIES}
	cp ../lp62-nattR1/OUTPUT/nattR1.pcap nattR1.pcap
	cp ../lp64-nattR2/OUTPUT/nattR2.pcap nattR2.pcap

# no I2-dump.txt file is produced.


