'\" t
.\"     Title: IPSEC_MAILKEY
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 10/06/2010
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "IPSEC_MAILKEY" "8" "10/06/2010" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ipsec_mailkey \- mail DNS records for Opportunistic Encryption
.SH "SYNOPSIS"
.HP \w'\fBipsec\fR\ 'u
\fBipsec\fR \-\-me\ \fImy@address\&.tld\fR [\-\-reverse\ \fI1\&.2\&.3\&.4\ aaa\fR] [\-\-forward\ \fIhostname\&.domain\&.tld\fR]
.SH "DESCRIPTION"
.PP
\fIMailkey\fR
is a meta\-program\&. It generates a script which will attempt to mail the TXT records required to enable Opportunistic Encryption (OE)\&.
.PP
An e\-mail address for the domain\(^as DNS administrator is derived from SOA records\&. The mail body and destination address are freely editable in the script\&.
.PP
If no administrator can be located, the output file will not be executable\&.
.PP
The
\fB\-\-me\fR
option sets the Reply\-to: address of the mail to be sent\&.
.PP
The
\fB\-\-forward\fR
hostname sets the domain name to be used for initiator\-only OE\&.
.PP
The
\fB\-\-reverse\fR
ip\-address sets the ip address to be used for full Opportunistic Encryption\&.
.SH "EXAMPLES"
.PP
\fBipsec mailkey \-\-me paul@xelerance\&.com \-\-forward bofh\&.xelerance\&.com\fR
.RS 4
creates the i\-OE record for use on bofh\&.xelerance\&.com\&.
.RE
.PP
\fBipsec mailkey \-\-me paul@xelerance\&.com \-\-reverse 193\&.110\&.157\&.17\fR
.RS 4
creates full\-OE record for use on bofh\&.xelerance\&.com\'s static IP address\&.
.RE
.SH "FILES"
.PP
/etc/ipsec\&.secrets
.SH "SEE ALSO"
.PP
ipsecshowhostkey(8),host(8)
.SH "HISTORY"
.PP
Written for the Linux FreeS/WAN project <\m[blue]\fBhttp://www\&.freeswan\&.org/\fR\m[]> by Sam Sgro\&.
