EXTRAFLAGS+=-I../../libpluto -I../../libpluto/lp124-peerB-R2
include ../../libpluto/lp12-parentR2/Makefile
EXTRAFLAGS+=-DSAMPLEDIR=\"${SAMPLEDIR}\"

# Local Variables:
# gdb-command: ""
# End Variables:
#
