EXTRAFLAGS+=-I..
EXTRAFLAGS+=-I../../libpluto
EXTRAFLAGS+=-I../../libpluto/lp10-parentI2
include ../../libpluto/lp10-parentI2/Makefile
EXTRAFLAGS+=-DSAMPLEDIR=\"${SAMPLEDIR}\"

# Local Variables:
# gdb-command: ""
# End Variables:
#
