SAMPLEDIR=../../libpluto/samples
TESTNAME=pickkeyI2
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}
CONNNAME=parker1--jj2
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME} OUTPUT/${TESTNAME}.pcap parentR1.pcap
ENDNAME=parker

EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_crypto.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_rsa.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_psk.o

pcapupdate:
	cp ../../libpluto/lp08-parentR1/OUTPUT/parentR1.pcap parentR1.pcap




