EXTRAFLAGS+=-I..
EXTRAFLAGS+=-I../../libpluto
EXTRAFLAGS+=-I../../libpluto/lp10-parentI2
include ../../libpluto/lp10-parentI2/Makefile
EXTRAFLAGS+=-DSAMPLEDIR=\"${SAMPLEDIR}\"

pcapupdate:
	#cp ../lp37-h2hR1/OUTPUT/h2hR1.pcap h2hR1.pcap



# Local Variables:
# gdb-command: ""
# End Variables:
#
