EXTRAFLAGS+=-I..
EXTRAFLAGS+=-I../../libpluto
EXTRAFLAGS+=-I../../libpluto/lp10-parentI2
include ../../libpluto/lp10-parentI2/Makefile
EXTRAFLAGS+=-DSAMPLEDIR=\"${SAMPLEDIR}\"

EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_crypto.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_rsa.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_psk.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/keymgmt.o

pcapupdate:
	#cp ../lp37-h2hR1/OUTPUT/h2hR1.pcap h2hR1.pcap



# Local Variables:
# gdb-command: ""
# End Variables:
#
