#!/bin/sh
#
# RCSID $Id: 110,v 1.16 2002/04/24 07:36:13 mcr Exp $
#

sg1=192.168.2.100
sg2=192.168.2.110
net1=192.168.5.0
net2=192.168.4.0
netany=0.0.0.0
hmask=255.255.255.255
nmask=255.255.255.0
anymask=0.0.0.0
vif0=ipsec0
vif1=ipsec1
phys0=eth0
phys1=eth2

case "$1" in
	# Driver load and initialisation
	setup)
#		depmod -a
#		modprobe ipsec
#		insmod ipsec
		insmod -m ipsec >/lib/modules/loadmaps/ipsec.map
		klogd -i -p
		ipsec tncfg --attach --virtual $vif0 --physical $phys0
		ipsec tncfg --attach --virtual $vif1 --physical $phys1
		ifconfig $vif0 $sg1
		ifconfig $vif1 207.236.55.216
		ipsec klipsdebug --all
		;;
	unload)
		ipsec tncfg --clear
		ifconfig ipsec0 down
		ifconfig ipsec1 down
		rmmod ipsec
		klogd -i
		route add -net seg4 gw gonzales
		;;
	# Transport mode
	tresp3desmd5)
		ipsec spi --edst $sg1 --spi 0x137 --proto esp --esp 3des-md5-96 \
			--enckey 0x663066306630663066306630663066306630663066306630 \
			--authkey 0x66306630663066306630663066306631

		ipsec spi --edst $sg2 --spi 0x127 --proto esp --esp 3des-md5-96 \
			--enckey 0x663066306630663066306630663066306630663066306630 \
			--authkey 0x66306630663066306630663066306630
		ipsec eroute --add --src $sg1/$hmask \
			--dst $sg2/$hmask \
			--edst $sg2 --spi 0x127 --proto esp
		route del $sg2
		route add -host $sg2 dev $vif0
		;;
	tresp3desmd5del)
		ipsec spi --edst $sg1 --spi 0x137 --proto esp --del

		route del $sg2
		ipsec eroute --del --src $sg1/$hmask --dst $sg2/$hmask
		ipsec spi --edst $sg2 --spi 0x127 --proto esp --del
		;;
	tresp3desahmd5)
		# return path
		ipsec spi --edst $sg1 --spi 0x135 --proto esp --esp 3des \
			--enckey 0x01030507090b0d0f11131517191b1d1f21232527292b2d2f
		ipsec spi --edst $sg1 --spi 0x136 --proto ah --ah hmac-md5-96 \
			--authkey 0x31333537393b3d3f41434547494b4d4f

		# forward path
		ipsec spi --edst $sg2 --spi 0x125 --proto esp --esp 3des \
			--enckey 0x51535557595b5d5f61636567696b6d6f71737577797b7d7f
		ipsec spi --edst $sg2 --spi 0x126 --proto ah --ah hmac-md5-96 \
			--authkey 0x81838587898b8d8f91939597999b9d9f
		ipsec spigrp $sg2 0x125 esp \
			$sg2 0x126 ah
		ipsec eroute --add --src $sg1/$hmask \
			--dst $sg2/$hmask \
			--edst $sg2 --spi 0x125 --proto esp
		route del $sg2
		route add -host $sg2 dev $vif0
		;;
	tresp3desahmd5del)
		ipsec spi --edst $sg1 --spi 0x135 --proto esp --del
		ipsec spi --edst $sg1 --spi 0x136 --proto ah --del

		route del $sg2
		ipsec eroute --del --src $sg1/$hmask --dst $sg2/$hmask
		ipsec spi --edst $sg2 --spi 0x125 --proto esp --del
		;;
	trahmd5)
		ipsec spi --edst $sg1 --spi 0x136 --proto ah --ah hmac-md5 \
			--authkey 0x66306630663031326630663066303137

		ipsec spi --edst $sg2 --spi 0x126 --proto ah --ah hmac-md5 \
			--authkey 0x66306630663031326630663066303136
		ipsec eroute --add --src $sg1/$hmask \
			--dst $sg2/$hmask \
			--edst $sg2 --spi 0x126 --proto ah
		route del $sg2
		route add -host $sg2 dev $vif0
		;;
	trahmd5del)
		ipsec spi --edst $sg1 --spi 0x136 --proto ah --del

		route del $sg2
		ipsec eroute --del --src $sg1/$hmask --dst $sg2/$hmask
		ipsec spi --edst $sg2 --spi 0x126 --proto ah --del
		;;
	trespdes)
		ipsec spi --edst $sg1 --spi 0x135 --proto esp --esp des \
			--enckey 0x6630663066303135

		ipsec spi --edst $sg2 --spi 0x125 --proto esp --esp des \
			--enckey 0x6630663066303134
		ipsec eroute --add --src $sg1/$hmask \
			--dst $sg2/$hmask \
			--edst $sg2 --spi 0x125 --proto esp
		route del $sg2
		route add -host $sg2 dev $vif0
		;;
	trespdesdel)
		ipsec spi --edst $sg1 --spi 0x135 --proto esp --del

		route del $sg2
#		route add -host $sg2 dev $vif0

		ipsec eroute --del --src $sg1/$hmask \
			--dst $sg2/$hmask
		ipsec spi --edst $sg2 --spi 0x125 --proto esp --del
		;;
	tresp3des)
		ipsec spi --edst $sg1 --spi 0x135 --proto esp --esp 3des \
			--enckey 0x663066306630663066306630663066306630663066306630

		route del $sg2
		route add -host $sg2 dev $vif0

		ipsec eroute --add --src $sg1/$hmask \
			--dst $sg2/$hmask \
			--edst $sg2 --spi 0x125 --proto esp
		ipsec spi --edst $sg2 --spi 0x125 --proto esp --esp 3des \
			--enckey 0x663066306630663066306630663066306630663066306630
		;;
	tresp3desdel)
		ipsec spi --edst $sg1 --spi 0x135 --proto esp --del

		route del $sg2
#		route add -host $sg2 dev $vif0

		ipsec eroute --del --src $sg1/$hmask \
			--dst $sg2/$hmask
		ipsec spi --edst $sg2 --spi 0x125 --proto esp --del
		;;
	# Tunnel mode
	tuesp3desmd5)
		# return path
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --esp 3des-md5-96 \
			--enckey 0x01030507090b0d0f11131517191b1d1f21232527292b2d2f \
			--authkey 0x31333537393b3d3f41434547494b4d4f

		# forward path
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --ip4 \
			--src $sg1 --dst $sg2
		ipsec spi --edst $sg2 --spi 0x105 --proto esp --esp 3des-md5-96 \
			--enckey 0x51535557595b5d5f61636567696b6d6f71737577797b7d7f \
			--authkey 0x81838587898b8d8f91939597999b9d9f
		ipsec spigrp $sg2 0x103 tun \
			$sg2 0x105 esp
		ipsec eroute --add --src $net1/$nmask \
			--dst $net2/$nmask \
			--edst $sg2 --spi 0x103 --proto tun
		route del $net2
		route add -net $net2 dev $vif0 gw $sg2
		;;
	tuesp3desmd5del)
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --del

		route del $net2
		ipsec eroute --del --src $net1/$nmask \
			--dst $net2/$nmask
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --del
		;;
	tuesp3desahmd5)
		# return path
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --esp 3des \
			--enckey 0x01030507090b0d0f11131517191b1d1f21232527292b2d2f
		ipsec spi --edst $sg1 --spi 0x116 --proto ah --ah hmac-md5-96 \
			--authkey 0x31333537393b3d3f41434547494b4d4f


		# forward path
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --ip4 \
			--src $sg1 --dst $sg2
		ipsec spi --edst $sg2 --spi 0x105 --proto esp --esp 3des \
			--enckey 0x51535557595b5d5f61636567696b6d6f71737577797b7d7f
		ipsec spi --edst $sg2 --spi 0x106 --proto ah --ah hmac-md5-96 \
			--authkey 0x81838587898b8d8f91939597999b9d9f
		ipsec eroute --add --src $net1/$nmask \
			--dst $net2/$nmask \
			--edst $sg2 --spi 0x103 --proto tun
		ipsec spigrp $sg2 0x103 tun \
			$sg2 0x105 esp \
			$sg2 0x106 ah
		route del $net2
		route add -net $net2 dev $vif0 gw $sg2
		;;
	tuesp3desahmd5del)
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --del
		ipsec spi --edst $sg1 --spi 0x116 --proto ah --del

		route del $net2
		ipsec eroute --del --src $net1/$nmask \
			--dst $net2/$nmask
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --del
		;;
	tuespdesmd5)
		# return path
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --esp des-md5-96 \
			--enckey 0x01030507090b0d0f \
			--authkey 0x31333537393b3d3f41434547494b4d4f

		# forward path
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --ip4 \
			--src $sg1 --dst $sg2
		ipsec spi --edst $sg2 --spi 0x105 --proto esp --esp des-md5-96 \
			--enckey 0x51535557595b5d5f \
			--authkey 0x81838587898b8d8f91939597999b9d9f
		ipsec spigrp $sg2 0x103 tun \
			$sg2 0x105 esp
		ipsec eroute --add --src $net1/$nmask \
			--dst $net2/$nmask \
			--edst $sg2 --spi 0x103 --proto tun
		route del $net2
		route add -net $net2 dev $vif0 gw $sg2
		;;
	tuespdesmd5del)
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --del

		route del $net2
		ipsec eroute --del --src $net1/$nmask \
			--dst $net2/$nmask
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --del
		;;
	tuespdesahmd5)
		# return path
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --esp des \
			--enckey 0x01030507090b0d0f
		ipsec spi --edst $sg1 --spi 0x116 --proto ah --ah hmac-md5-96 \
			--authkey 0x31333537393b3d3f41434547494b4d4f


		# forward path
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --ip4 \
			--src $sg1 --dst $sg2
		ipsec spi --edst $sg2 --spi 0x105 --proto esp --esp des \
			--enckey 0x51535557595b5d5f
		ipsec spi --edst $sg2 --spi 0x106 --proto ah --ah hmac-md5-96 \
			--authkey 0x81838587898b8d8f91939597999b9d9f
		ipsec eroute --add --src $net1/$nmask \
			--dst $net2/$nmask \
			--edst $sg2 --spi 0x103 --proto tun
		ipsec spigrp $sg2 0x103 tun \
			$sg2 0x105 esp \
			$sg2 0x106 ah
		route del $net2
		route add -net $net2 dev $vif0 gw $sg2
		;;
	tuespdesahmd5del)
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --del
		ipsec spi --edst $sg1 --spi 0x116 --proto ah --del

		route del $net2
		ipsec eroute --del --src $net1/$nmask \
			--dst $net2/$nmask
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --del
		;;
	tuesp3dessha1)
		# return path
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --esp 3des-sha1-96 \
			--enckey 0x01030507090b0d0f11131517191b1d1f21232527292b2d2f \
			--authkey 0x31333537393b3d3f41434547494b4d4f51535557

		# forward path
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --ip4 \
			--src $sg1 --dst $sg2
		ipsec spi --edst $sg2 --spi 0x105 --proto esp --esp 3des-sha1-96 \
			--enckey 0x51535557595b5d5f61636567696b6d6f71737577797b7d7f \
			--authkey 0x81838587898b8d8f91939597999b9d9fa1a3a5a7
		ipsec spigrp $sg2 0x103 tun \
			$sg2 0x105 esp
		ipsec eroute --add --src $net1/$nmask \
			--dst $net2/$nmask \
			--edst $sg2 --spi 0x103 --proto tun
		route del $net2
		route add -net $net2 dev $vif0 gw $sg2
		;;
	tuesp3dessha1del)
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --del

		route del $net2
		ipsec eroute --del --src $net1/$nmask \
			--dst $net2/$nmask
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --del
		;;
	tuesp3desahsha1)
		# return path
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --esp 3des \
			--enckey 0x01030507090b0d0f11131517191b1d1f21232527292b2d2f
		ipsec spi --edst $sg1 --spi 0x116 --proto ah --ah hmac-sha1-96 \
			--authkey 0x31333537393b3d3f41434547494b4d4f51535557


		# forward path
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --ip4 \
			--src $sg1 --dst $sg2
		ipsec spi --edst $sg2 --spi 0x105 --proto esp --esp 3des \
			--enckey 0x51535557595b5d5f61636567696b6d6f71737577797b7d7f
		ipsec spi --edst $sg2 --spi 0x106 --proto ah --ah hmac-sha1-96 \
			--authkey 0x81838587898b8d8f91939597999b9d9fa1a3a5a7
		ipsec eroute --add --src $net1/$nmask \
			--dst $net2/$nmask \
			--edst $sg2 --spi 0x103 --proto tun
		ipsec spigrp $sg2 0x103 tun \
			$sg2 0x105 esp \
			$sg2 0x106 ah
		route del $net2
		route add -net $net2 dev $vif0 gw $sg2
		;;
	tuesp3desahsha1del)
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --del
		ipsec spi --edst $sg1 --spi 0x116 --proto ah --del

		route del $net2
		ipsec eroute --del --src $net1/$nmask \
			--dst $net2/$nmask
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --del
		;;
	tuesp3des)
		# return path
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --esp 3des \
			--enckey 0x01030507090b0d0f11131517191b1d1f21232527292b2d2f

		# forward path
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --ip4 \
			--src $sg1 --dst $sg2
		ipsec spi --edst $sg2 --spi 0x105 --proto esp --esp 3des \
			--enckey 0x51535557595b5d5f61636567696b6d6f71737577797b7d7f
		ipsec eroute --add --src $net1/$nmask \
			--dst $net2/$nmask \
			--edst $sg2 --spi 0x103 --proto tun
		ipsec spigrp $sg2 0x103 tun \
			$sg2 0x105 esp
		route del $net2
		route add -net $net2 dev $vif0 gw $sg2
		;;
	tuesp3desdel)
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --del

		route del $net2
		ipsec eroute --del --src $net1/$nmask \
			--dst $net2/$nmask
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --del
		;;
	tuespdes)
		# return path
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --esp des \
			--enckey 0x01030507090b0d0f

		# forward path
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --ip4 \
			--src $sg1 --dst $sg2
		ipsec spi --edst $sg2 --spi 0x105 --proto esp --esp des \
			--enckey 0x51535557595b5d5f
		ipsec eroute --add --src $net1/$nmask \
			--dst $net2/$nmask \
			--edst $sg2 --spi 0x103 --proto tun
		ipsec spigrp $sg2 0x103 tun \
			$sg2 0x105 esp
		route del $net2
		route add -net $net2 dev $vif0 gw $sg2
		;;
	tuespdesdel)
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --del

		route del $net2
		ipsec eroute --del --src $net1/$nmask \
			--dst $net2/$nmask
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --del
		;;
	tuahmd5)
		# return path
		ipsec spi --edst $sg1 --spi 0x116 --proto ah --ah hmac-md5-96 \
			--authkey 0x31333537393b3d3f41434547494b4d4f


		# forward path
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --ip4 \
			--src $sg1 --dst $sg2
		ipsec spi --edst $sg2 --spi 0x106 --proto ah --ah hmac-md5-96 \
			--authkey 0x81838587898b8d8f91939597999b9d9f
		ipsec eroute --add --src $net1/$nmask \
			--dst $net2/$nmask \
			--edst $sg2 --spi 0x103 --proto tun
		ipsec spigrp $sg2 0x103 tun \
			$sg2 0x106 ah
		route del $net2
		route add -net $net2 dev $vif0 gw $sg2
		;;
	tuahmd5del)
		ipsec spi --edst $sg1 --spi 0x116 --proto ah --del

		route del $net2
		ipsec eroute --del --src $net1/$nmask \
			--dst $net2/$nmask
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --del
		;;
	tuahsha1)
		# return path
		ipsec spi --edst $sg1 --spi 0x116 --proto ah --ah hmac-sha1-96 \
			--authkey 0x31333537393b3d3f41434547494b4d4f51535557


		# forward path
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --ip4 \
			--src $sg1 --dst $sg2
		ipsec spi --edst $sg2 --spi 0x106 --proto ah --ah hmac-sha1-96 \
			--authkey 0x81838587898b8d8f91939597999b9d9fa1a3a5a7
		ipsec eroute --add --src $net1/$nmask \
			--dst $net2/$nmask \
			--edst $sg2 --spi 0x103 --proto tun
		ipsec spigrp $sg2 0x103 tun \
			$sg2 0x106 ah
		route del $net2
		route add -net $net2 dev $vif0 gw $sg2
		;;
	tuahsha1del)
		ipsec spi --edst $sg1 --spi 0x116 --proto ah --del

		route del $net2
		ipsec eroute --del --src $net1/$nmask \
			--dst $net2/$nmask
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --del
		;;
	tuespnullmd5)
		# return path
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --esp null-md5-96 \
			--authkey 0x31333537393b3d3f41434547494b4d4f

		# forward path
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --ip4 \
			--src $sg1 --dst $sg2
		ipsec spi --edst $sg2 --spi 0x105 --proto esp --esp null-md5-96 \
			--authkey 0x81838587898b8d8f91939597999b9d9f
		ipsec spigrp $sg2 0x103 tun \
			$sg2 0x105 esp
		ipsec eroute --add --src $net1/$nmask \
			--dst $net2/$nmask \
			--edst $sg2 --spi 0x103 --proto tun
		route del $net2
		route add -net $net2 dev $vif0 gw $sg2
		;;
	tuespnullmd5del)
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --del

		route del $net2
		ipsec eroute --del --src $net1/$nmask \
			--dst $net2/$nmask
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --del
		;;
	turoadme)
		# return path
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --esp des \
			--enckey 0x6630663066303131
		ipsec spi --edst $sg1 --spi 0x116 --proto ah --ah md5 \
			--authkey 0x66306630663031326630663066303131

		# forward path
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --ip4 \
			--src $sg1 --dst $sg2
		ipsec spi --edst $sg2 --spi 0x105 --proto esp --esp des \
			--enckey 0x6630663066303130
		ipsec spi --edst $sg2 --spi 0x106 --proto ah --ah md5 \
			--authkey 0x66306630663031326630663066303130
		ipsec spigrp $sg2 0x103 tun \
			$sg2 0x105 esp \
			$sg2 0x106 ah
		ipsec eroute --add --src $sg1/$hmask \
			--dst $net2/$nmask \
			--edst $sg2 --spi 0x103 --proto tun
		route del $net2
		route add -net $net2 dev $vif0 gw $sg2
		;;
	turoadyou)
		# return path
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --esp des \
			--enckey 0x6630663066303131
		ipsec spi --edst $sg1 --spi 0x116 --proto ah --ah md5 \
			--authkey 0x66306630663031326630663066303131

		# forward path
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --ip4 \
			--src $sg1 --dst $sg2
		ipsec spi --edst $sg2 --spi 0x105 --proto esp --esp des \
			--enckey 0x6630663066303130
		ipsec spi --edst $sg2 --spi 0x106 --proto ah --ah md5 \
			--authkey 0x66306630663031326630663066303130
		ipsec spigrp $sg2 0x103 tun \
			$sg2 0x105 esp \
			$sg2 0x106 ah
		ipsec eroute --add --src $net1/$nmask \
			--dst $sg2/$hmask \
			--edst $sg2 --spi 0x103 --proto tun
		route del $sg2
		route add -host $sg2 dev $vif0
		;;
	turoadyoudel)
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --del
		ipsec spi --edst $sg1 --spi 0x116 --proto ah --del

		route del $sg2
		ipsec eroute --del --src $net1/$nmask \
			--dst $sg2/$hmask
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --del
		;;
	tuany2sg)
		# return path
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --esp 3des-md5-96 \
			--enckey 0x01030507090b0d0f11131517191b1d1f21232527292b2d2f \
			--authkey 0x31333537393b3d3f41434547494b4d4f

		# forward path
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --ip4 \
			--src $sg1 --dst $sg2
		ipsec spi --edst $sg2 --spi 0x105 --proto esp --esp 3des-md5-96 \
			--enckey 0x51535557595b5d5f61636567696b6d6f71737577797b7d7f \
			--authkey 0x81838587898b8d8f91939597999b9d9f
		ipsec spigrp $sg2 0x103 tun \
			$sg2 0x105 esp
		ipsec eroute --add --src $netany/$anymask \
			--dst $sg2/$hmask \
			--edst $sg2 --spi 0x103 --proto tun
		route del $sg2
		route add -host $sg2 dev $vif0
		;;
	tuany2sgdel)
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --del

		route del $sg2
		ipsec eroute --del --src $netany/$anymask \
			--dst $sg2/$hmask
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --del
		;;
	tuany2subnet)
		# return path
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --esp 3des-md5-96 \
			--enckey 0x01030507090b0d0f11131517191b1d1f21232527292b2d2f \
			--authkey 0x31333537393b3d3f41434547494b4d4f

		# forward path
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --ip4 \
			--src $sg1 --dst $sg2
		ipsec spi --edst $sg2 --spi 0x105 --proto esp --esp 3des-md5-96 \
			--enckey 0x51535557595b5d5f61636567696b6d6f71737577797b7d7f \
			--authkey 0x81838587898b8d8f91939597999b9d9f
		ipsec spigrp $sg2 0x103 tun \
			$sg2 0x105 esp
		ipsec eroute --add --src $netany/$anymask \
			--dst $net2/$nmask \
			--edst $sg2 --spi 0x103 --proto tun
		route del $net2
		route add -net $net2 dev $vif0 gw $sg2
		;;
	tuany2subnetdel)
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --del

		route del $net2
		route add -net $net2 dev eth0 gw $sg2
		ipsec eroute --del --src $netany/$anymask \
			--dst $net2/$nmask
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --del
		;;
	tgesp3desahmd5)
		# return path
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --esp 3des \
			--enckey 0x01030507090b0d0f11131517191b1d1f21232527292b2d2f
		ipsec spi --edst $sg1 --spi 0x116 --proto ah --ah hmac-md5-96 \
			--authkey 0x31333537393b3d3f41434547494b4d4f


		# forward path
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --ip4 \
			--src $sg1 --dst $sg2
		ipsec spi --edst $sg2 --spi 0x105 --proto esp --esp 3des \
			--enckey 0x51535557595b5d5f61636567696b6d6f71737577797b7d7f
		ipsec spi --edst $sg2 --spi 0x106 --proto ah --ah hmac-md5-96 \
			--authkey 0x81838587898b8d8f91939597999b9d9f
		ipsec eroute --add --src $sg1/$hmask \
			--dst $sg2/$hmask \
			--edst $sg2 --spi 0x103 --proto tun
		ipsec spigrp $sg2 0x103 tun \
			$sg2 0x105 esp \
			$sg2 0x106 ah
		route del $sg2
		route add -host $sg2 dev $vif0
		;;
	tgesp3desahmd5del)
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --del
		ipsec spi --edst $sg1 --spi 0x116 --proto ah --del

		route del $sg2
		ipsec eroute --del --src $sg1/$hmask \
			--dst $sg2/$hmask
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --del
		;;
	tgespdes)
		# return path
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --esp des \
			--enckey 0x6630663066303139
		#spi --edst $sg1 --spi 0x116 --proto ah --ah hmac-md5 \
		#	--authkey 0x66306630663031326630663066303139

		# forward path
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --ip4 \
			--src $sg1 --dst $sg2
		ipsec spi --edst $sg2 --spi 0x105 --proto esp --esp des \
			--enckey 0x6630663066303138
		#spi --edst $sg2 --spi 0x106 --proto ah --ah hmac-md5 \
		#	--authkey 0x66306630663031326630663066303138
		ipsec spigrp $sg2 0x103 tun \
			$sg2 0x105 esp \
		#	$sg2 0x106 ah
		ipsec eroute --add --src $sg1/$hmask \
			--dst $sg2/$hmask \
			--edst $sg2 --spi 0x103 --proto tun
		route del $sg2
		route add -host $sg2 dev $vif0
		;;
	tgespdesdel)
		# return path
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --del
		ipsec spi --edst $sg1 --spi 0x116 --proto ah --del

		# forward path
		route del $sg2
#		route add -host $sg2 dev $vif0
		ipsec eroute --del --src $sg1/$hmask \
			--dst $sg2/$hmask
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --del
		;;
	tgahmd5)
		# return path
		#spi --edst $sg1 --spi 0x115 --proto esp --esp des \
		#	--enckey 0x6630663066303139
		ipsec spi --edst $sg1 --spi 0x116 --proto ah --ah hmac-md5 \
			--authkey 0x66306630663031326630663066303139

		# forward path
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --ip4 \
			--src $sg1 --dst $sg2
		#spi --edst $sg2 --spi 0x105 --proto esp --esp des \
		#	--enckey 0x6630663066303138
		ipsec spi --edst $sg2 --spi 0x106 --proto ah --ah hmac-md5 \
			--authkey 0x66306630663031326630663066303138
		ipsec spigrp $sg2 0x103 tun \
			$sg2 0x106 ah
		#	$sg2 0x105 esp \
		ipsec eroute --add --src $sg1/$hmask \
			--dst $sg2/$hmask \
			--edst $sg2 --spi 0x103 --proto tun
		route del $sg2
		route add -host $sg2 dev $vif0
		;;
	tgahmd5del)
		# return path
		ipsec spi --edst $sg1 --spi 0x115 --proto esp --del
		ipsec spi --edst $sg1 --spi 0x116 --proto ah --del

		# forward path
		route del $sg2
#		route add -host $sg2 dev $vif0
		ipsec eroute --del --src $sg1/$hmask \
			--dst $sg2/$hmask
		ipsec spi --edst $sg2 --spi 0x103 --proto tun --del
		;;
	proc)
		cat /proc/net/ipsec_*
		;;
esac

#
# $Log: 110,v $
# Revision 1.16  2002/04/24 07:36:13  mcr
# Moved from ./klips/test/100/110,v
#
# Revision 1.15  1999/06/13 07:25:20  rgb
# Change spis to avoid collision between tests.
#
# Revision 1.14  1999/06/10 16:37:47  rgb
# Ditch IVs.
#
# Revision 1.13  1999/06/10 16:09:00  rgb
# Change spis to avoid clash between trah and tresp.
#
# Revision 1.12  1999/05/25 21:27:05  rgb
# Fix test subnet numbers that have moved.
#
# Revision 1.11  1999/04/06 04:54:32  rgb
# Fix/Add RCSID Id: and Log: bits to make PHMDs happy.  This includes
# patch shell fixes.
#
#
