/*
 * List of some useful object identifiers (OIDs)
 *
 * Copyright (C) 2003-2004 Andreas Steffen, Zuercher Hochschule Winterthur
 * Copyright (C) 2014 Tuomo Soini <tis@foobar.fi>
 *
 * This file has been generated by the script lib/libswan/oid.pl
 * Do not edit manually!
 */
#include "oid.h"

const oid_t oid_names[] = {
	/* octet, down, next, name */
	{ 0x02,                       1,   7, "ITU-T Administration"    },  /*   0 */
	{   0x82,                     1,   0, ""                        },  /*   1 */
	{     0x06,                   1,   0, "Germany ITU-T member"    },  /*   2 */
	{       0x01,                 1,   0, "Deutsche Telekom AG"     },  /*   3 */
	{         0x0A,               1,   0, ""                        },  /*   4 */
	{           0x07,             1,   0, ""                        },  /*   5 */
	{             0x14,           0,   0, "ND"                      },  /*   6 */
	{ 0x09,                       1,  18, "data"                    },  /*   7 */
	{   0x92,                     1,   0, ""                        },  /*   8 */
	{     0x26,                   1,   0, ""                        },  /*   9 */
	{       0x89,                 1,   0, ""                        },  /*  10 */
	{         0x93,               1,   0, ""                        },  /*  11 */
	{           0xF2,             1,   0, ""                        },  /*  12 */
	{             0x2C,           1,   0, ""                        },  /*  13 */
	{               0x64,         1,   0, "pilot"                   },  /*  14 */
	{                 0x01,       1,   0, "pilotAttributeType"      },  /*  15 */
	{                   0x01,     0,  17, "UID"                     },  /*  16 */
	{                   0x19,     0,   0, "DC"                      },  /*  17 */
	{ 0x55,                       1,  51, "X.500"                   },  /*  18 */
	{   0x04,                     1,  36, "X.509"                   },  /*  19 */
	{     0x03,                   0,  21, "CN"                      },  /*  20 */
	{     0x04,                   0,  22, "S"                       },  /*  21 */
	{     0x05,                   0,  23, "SN"                      },  /*  22 */
	{     0x06,                   0,  24, "C"                       },  /*  23 */
	{     0x07,                   0,  25, "L"                       },  /*  24 */
	{     0x08,                   0,  26, "ST"                      },  /*  25 */
	{     0x0A,                   0,  27, "O"                       },  /*  26 */
	{     0x0B,                   0,  28, "OU"                      },  /*  27 */
	{     0x0C,                   0,  29, "T"                       },  /*  28 */
	{     0x0D,                   0,  30, "D"                       },  /*  29 */
	{     0x24,                   0,  31, "userCertificate"         },  /*  30 */
	{     0x29,                   0,  32, "N"                       },  /*  31 */
	{     0x2A,                   0,  33, "G"                       },  /*  32 */
	{     0x2B,                   0,  34, "I"                       },  /*  33 */
	{     0x2D,                   0,  35, "ID"                      },  /*  34 */
	{     0x48,                   0,   0, "role"                    },  /*  35 */
	{   0x1d,                     1,   0, "id-ce"                   },  /*  36 */
	{     0x09,                   0,  38, "subjectDirectoryAttrs"   },  /*  37 */
	{     0x0E,                   0,  39, "subjectKeyIdentifier"    },  /*  38 */
	{     0x0F,                   0,  40, "keyUsage"                },  /*  39 */
	{     0x10,                   0,  41, "privateKeyUsagePeriod"   },  /*  40 */
	{     0x11,                   0,  42, "subjectAltName"          },  /*  41 */
	{     0x12,                   0,  43, "issuerAltName"           },  /*  42 */
	{     0x13,                   0,  44, "basicConstraints"        },  /*  43 */
	{     0x15,                   0,  45, "reasonCode"              },  /*  44 */
	{     0x1F,                   0,  46, "crlDistributionPoints"   },  /*  45 */
	{     0x20,                   0,  47, "certificatePolicies"     },  /*  46 */
	{     0x23,                   0,  48, "authorityKeyIdentifier"  },  /*  47 */
	{     0x25,                   0,  49, "extendedKeyUsage"        },  /*  48 */
	{     0x37,                   0,  50, "targetInformation"       },  /*  49 */
	{     0x38,                   0,   0, "noRevAvail"              },  /*  50 */
	{ 0x2A,                       1,  80, ""                        },  /*  51 */
	{   0x86,                     1,   0, ""                        },  /*  52 */
	{     0x48,                   1,   0, ""                        },  /*  53 */
	{       0x86,                 1,   0, ""                        },  /*  54 */
	{         0xF7,               1,   0, ""                        },  /*  55 */
	{           0x0D,             1,   0, "RSADSI"                  },  /*  56 */
	{             0x01,           1,  77, "PKCS"                    },  /*  57 */
	{               0x01,         1,  67, "PKCS-1"                  },  /*  58 */
	{                 0x01,       0,  60, "rsaEncryption"           },  /*  59 */
	{                 0x02,       0,  61, "md2WithRSAEncryption"    },  /*  60 */
	{                 0x04,       0,  62, "md5WithRSAEncryption"    },  /*  61 */
	{                 0x05,       0,  63, "sha-1WithRSAEncryption"  },  /*  62 */
	{                 0x0B,       0,  64, "sha256WithRSAEncryption" },  /*  63 */
	{                 0x0C,       0,  65, "sha384WithRSAEncryption" },  /*  64 */
	{                 0x0D,       0,  66, "sha512WithRSAEncryption" },  /*  65 */
	{                 0x0E,       0,   0, "sha224WithRSAEncryption" },  /*  66 */
	{               0x07,         1,  74, "PKCS-7"                  },  /*  67 */
	{                 0x01,       0,  69, "data"                    },  /*  68 */
	{                 0x02,       0,  70, "signedData"              },  /*  69 */
	{                 0x03,       0,  71, "envelopedData"           },  /*  70 */
	{                 0x04,       0,  72, "signedAndEnvelopedData"  },  /*  71 */
	{                 0x05,       0,  73, "digestedData"            },  /*  72 */
	{                 0x06,       0,   0, "encryptedData"           },  /*  73 */
	{               0x09,         1,   0, "PKCS-9"                  },  /*  74 */
	{                 0x01,       0,  76, "E"                       },  /*  75 */
	{                 0x02,       0,   0, "unstructuredName"        },  /*  76 */
	{             0x02,           1,   0, "digestAlgorithm"         },  /*  77 */
	{               0x02,         0,  79, "md2"                     },  /*  78 */
	{               0x05,         0,   0, "md5"                     },  /*  79 */
	{ 0x2B,                       1, 133, ""                        },  /*  80 */
	{   0x06,                     1, 121, "dod"                     },  /*  81 */
	{     0x01,                   1,   0, "internet"                },  /*  82 */
	{       0x04,                 1,  92, "private"                 },  /*  83 */
	{         0x01,               1,   0, "enterprise"              },  /*  84 */
	{           0x89,             1,   0, ""                        },  /*  85 */
	{             0x31,           1,   0, ""                        },  /*  86 */
	{               0x01,         1,   0, ""                        },  /*  87 */
	{                 0x01,       1,   0, ""                        },  /*  88 */
	{                   0x02,     1,   0, ""                        },  /*  89 */
	{                     0x02,   1,   0, ""                        },  /*  90 */
	{                       0x4B, 0,   0, "TCGID"                   },  /*  91 */
	{       0x05,                 1,   0, "security"                },  /*  92 */
	{         0x05,               1,   0, "mechanisms"              },  /*  93 */
	{           0x07,             1,   0, "id-pkix"                 },  /*  94 */
	{             0x01,           1,  97, "id-pe"                   },  /*  95 */
	{               0x01,         0,   0, "authorityInfoAccess"     },  /*  96 */
	{             0x03,           1, 107, "id-kp"                   },  /*  97 */
	{               0x01,         0,  99, "serverAuth"              },  /*  98 */
	{               0x02,         0, 100, "clientAuth"              },  /*  99 */
	{               0x03,         0, 101, "codeSigning"             },  /* 100 */
	{               0x04,         0, 102, "emailProtection"         },  /* 101 */
	{               0x05,         0, 103, "ipsecEndSystem"          },  /* 102 */
	{               0x06,         0, 104, "ipsecTunnel"             },  /* 103 */
	{               0x07,         0, 105, "ipsecUser"               },  /* 104 */
	{               0x08,         0, 106, "timeStamping"            },  /* 105 */
	{               0x09,         0,   0, "ocspSigning"             },  /* 106 */
	{             0x0A,           1, 112, "id-aca"                  },  /* 107 */
	{               0x01,         0, 109, "authenticationInfo"      },  /* 108 */
	{               0x02,         0, 110, "accessIdentity"          },  /* 109 */
	{               0x03,         0, 111, "chargingIdentity"        },  /* 110 */
	{               0x04,         0,   0, "group"                   },  /* 111 */
	{             0x30,           1,   0, "id-ad"                   },  /* 112 */
	{               0x01,         1,   0, "ocsp"                    },  /* 113 */
	{                 0x01,       0, 115, "basic"                   },  /* 114 */
	{                 0x02,       0, 116, "nonce"                   },  /* 115 */
	{                 0x03,       0, 117, "crl"                     },  /* 116 */
	{                 0x04,       0, 118, "response"                },  /* 117 */
	{                 0x05,       0, 119, "noCheck"                 },  /* 118 */
	{                 0x06,       0, 120, "archiveCutoff"           },  /* 119 */
	{                 0x07,       0,   0, "serviceLocator"          },  /* 120 */
	{   0x0E,                     1, 126, "oiw"                     },  /* 121 */
	{     0x03,                   1,   0, "secsig"                  },  /* 122 */
	{       0x02,                 1,   0, "algorithms"              },  /* 123 */
	{         0x1A,               0, 125, "sha-1"                   },  /* 124 */
	{         0x1D,               0,   0, "sha-1WithRSASignature"   },  /* 125 */
	{   0x24,                     1,   0, "TeleTrusT"               },  /* 126 */
	{     0x03,                   1,   0, "algorithm"               },  /* 127 */
	{       0x03,                 1,   0, "signatureAlgorithm"      },  /* 128 */
	{         0x01,               1,   0, "rsaSignature"            },  /* 129 */
	{           0x02,             0, 131, "rsaSigWithripemd160"     },  /* 130 */
	{           0x03,             0, 132, "rsaSigWithripemd128"     },  /* 131 */
	{           0x04,             0,   0, "rsaSigWithripemd256"     },  /* 132 */
	{ 0x60,                       1,   0, ""                        },  /* 133 */
	{   0x86,                     1,   0, ""                        },  /* 134 */
	{     0x48,                   1,   0, ""                        },  /* 135 */
	{       0x01,                 1,   0, "organization"            },  /* 136 */
	{         0x65,               1, 144, "gov"                     },  /* 137 */
	{           0x03,             1,   0, "csor"                    },  /* 138 */
	{             0x04,           1,   0, "nistalgorithm"           },  /* 139 */
	{               0x02,         1,   0, "hashalgs"                },  /* 140 */
	{                 0x01,       0, 142, "id-SHA-256"              },  /* 141 */
	{                 0x02,       0, 143, "id-SHA-384"              },  /* 142 */
	{                 0x03,       0,   0, "id-SHA-512"              },  /* 143 */
	{         0x86,               1,   0, ""                        },  /* 144 */
	{           0xf8,             1,   0, ""                        },  /* 145 */
	{             0x42,           1,   0, ""                        },  /* 146 */
	{               0x01,         1,   0, ""                        },  /* 147 */
	{                 0x01,       0, 149, "nsCertType"              },  /* 148 */
	{                 0x03,       0, 150, "nsRevocationUrl"         },  /* 149 */
	{                 0x0d,       0,   0, "nsComment"               }   /* 150 */
};
