# -*- makefile -*-
CONNNAME=home
ENDNAME=davecert-ca
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME} OUTPUT/h2hI2.pcap h2hR1.pcap
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}

TESTNAME=h2hI2

PCAPDEPENDENCIES = ../lp202-ca-h2hR1/OUTPUT/h2hR1.pcap
include ../Makefile.pcapupdate

pcapupdate: ${PCAPDEPENDENCIES}
	cp ../lp202-ca-h2hR1/OUTPUT/h2hR1.pcap h2hR1.pcap
