.\"     Title: _CONFREAD
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/14/2008
.\"    Manual: 28 Oct 2006
.\"    Source: 28 Oct 2006
.\"
.TH "_CONFREAD" "8" "11/14/2008" "28 Oct 2006" "28 Oct 2006"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ipsec _confread - internal routing to parse config file
.SH "DESCRIPTION"
.PP
\fI_confread\fR
is an internal script used for parsing /etc/ipsec\.conf into a canonical format\.
.SH "OBSOLETE"
.PP
\fI_confread\fR
is going to be obsoleted in the next major release of Openswan in favour of the
\fIaddcon\fR
code\. The new code will load all the connections much faster then the current scripts that can takes minutes to load a few hunderd conns, and requires awk and sed commands not always available in their full versions, such as with busybox on embedded platforms\. The old alternative to this called
\fIstarter\fR
will also be removed as obsolete for the new
\fIaddcon\fR
code\.
.SH "SEE ALSO"
.PP
\fBipsec\fR(8),
\fBipsec_conf\fR(8)
.SH "HISTORY"
.PP
Man page written for the Linux FreeS/WAN project <\fIhttp://www\.freeswan\.org/\fR> by Michael Richardson\. Program written by Henry Spencer\.
