'\" t
.\"     Title: IPSEC_PF_KEY
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 10/06/2010
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "IPSEC_PF_KEY" "5" "10/06/2010" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ipsec_pf_key \- lists PF_KEY sockets registered with KLIPS
.SH "SYNOPSIS"
.HP \w'\fBcat\fR\ 'u
\fBcat\fR \fI/proc/net/pf_key\fR
.SH "STACK"
.PP
Note that pf_key is only supported on the KLIPS and MAST stacks\&. It is not supported on any other stack\&.
.SH "DESCRIPTION"
.PP
/proc/net/pf_key
is a read\-only file which lists the presently open PF_KEY sockets on the local system and their parameters\&.
.PP
Each line lists one PF_KEY socket\&. A table entry consists of:
.PP
+
.RS 4
sock pointer (sock)
.RE
.PP
+
.RS 4
PID of the socket owner (pid)
.RE
.PP
+
.RS 4
flag to indicate if the socket is dead (d)
.RE
.PP
+
.RS 4
socket wait queue (sleep)
.RE
.PP
+
.RS 4
socket pointer (socket)
.RE
.PP
+
.RS 4
next socket in chain (next)
.RE
.PP
+
.RS 4
previous socket in chain (prev)
.RE
.PP
+
.RS 4
last socket error (e)
.RE
.PP
+
.RS 4
pointer to destruct routine (destruct)
.RE
.PP
+
.RS 4
is this a reused socket (r)
.RE
.PP
+
.RS 4
has this socket been zapped (z)
.RE
.PP
+
.RS 4
socket family to which this socket belongs (fa)
.RE
.PP
+
.RS 4
local port number (n)
.RE
.PP
+
.RS 4
protocol version number (p)
.RE
.PP
+
.RS 4
Receive queue bytes committed (r)
.RE
.PP
+
.RS 4
Transmit queue bytes committed (w)
.RE
.PP
+
.RS 4
option memory allocations (o)
.RE
.PP
+
.RS 4
size of send buffer in bytes (sndbf)
.RE
.PP
+
.RS 4
timestamp in seconds (stamp)
.RE
.PP
+
.RS 4
socket flags (Flags)
.RE
.PP
+
.RS 4
socket type (Type)
.RE
.PP
+
.RS 4
connection state (St)
.RE
.SH "EXAMPLES"
.PP
\fBc3b8c140 3553 0 c0599818 c05997fc 0 0 0 0 1 0 15 0 2 0 0 0 65535 0\&.103232 00000000 00000003 01\fR
.RS 4
.RE
.PP
shows that there is one pf_key socket set up that starts at
\fBc3b8c140\fR, whose owning process has PID
3553, the socket is not dead, its wait queue is at
\fBc0599818\fR, whose owning socket is at
\fBc05997fc\fR, with no other sockets in the chain, no errors, no destructor, it is a reused socket which has not been zapped, from protocol family
15
(PF_KEY), local port number
0, protocol socket version
2, no memory allocated to transmit, receive or option queues, a send buffer of almost
\fB64kB\fR, a timestamp of
0\&.103232, no flags set, type
3, in state
1\&.
.SH "FILES"
.PP
/proc/net/pf_key
.SH "SEE ALSO"
.PP
ipsec(8), ipsec_manual(8), ipsec_eroute(5), ipsec_spi(5), ipsec_spigrp(5), ipsec_klipsdebug(5), ipsec_tncfg(8), ipsec_version(5)
.SH "HISTORY"
.PP
Written for the Linux FreeS/WAN project <\m[blue]\fBhttp://www\&.freeswan\&.org/\fR\m[]> by Richard Guy Briggs\&.
