.\"     Title: IPSEC_PF_KEY
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/14/2008
.\"    Manual: 17 Oct 2001
.\"    Source: 17 Oct 2001
.\"
.TH "IPSEC_PF_KEY" "8" "11/14/2008" "17 Oct 2001" "17 Oct 2001"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pf_key - shows pfkey messages emitted by the kernel when using the KLIPS or MAST stack.
.SH "SYNOPSIS"
.HP 7
\fBpf_key\fR \-\-ah \-\-esp \-\-ipip \-\-ipcomp \-\-daemon \fIfilehmac\-md5\-96\fR | \fIhmac\-sha1\-96\fR 
.SH "STACK"
.PP
Note that pf_key is only supported on the KLIPS and MAST stacks\. It is not supported on any other stack\.
.SH "DESCRIPTION"
.PP
\fBpf_key\fR
is a program to open a PF_KEY socket and print all messages that are received from it\. With no options, it will register itself to receive key requests for AH, ESP, IPIP and IPCOMP security associations\. If given more specific options, then it will listen only to those protocols which are listed\.
.PP
If the messages are recognized, the messages will be decoded\.
.PP
If the option
\fB\-\-daemon\fR
is provided, then after doing the registrations, the program will fork into the background\. The provided file will be opened and the process ID of the background process will be written to it\. This option is present to present race conditions in regression testing\.
.SH "FILES"
.PP
/proc/net/pf_key
.SH "SEE ALSO"
.PP
\fBpf_key\fR(5),
\fBipsec\fR(8),
\fBipsec_manual\fR(8),
\fBipsec_eroute\fR(5),
\fBipsec_spi\fR(5),
\fBipsec_spigrp\fR(5),
\fBipsec_klipsdebug\fR(5),
\fBipsec_tncfg\fR(8),
\fBipsec_version\fR(5)
.SH "HISTORY"
.PP
Written for the Linux FreeS/WAN project <\fIhttp://www\.freeswan\.org/\fR> by Michael Richardson <mcr@freeswan\.org>
