include ../lp15-respondself/Makefile

PCAPDEPENDENCIES = ../lp36-h2hI1/OUTPUT/h2hI1.pcap
include ../Makefile.pcapupdate

pcapupdate: ${PCAPDEPENDENCIES}
	cp ../lp36-h2hI1/OUTPUT/h2hI1.pcap h2hI1.pcap


# Local Variables:
# gdb-command: ""
# End Variables:
#
