EXTRAFLAGS+=-I../../libpluto
include ../../libpluto/lp12-parentR2/Makefile
EXTRAFLAGS+=-DSAMPLEDIR=\"${SAMPLEDIR}\"

EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_crypto.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_rsa.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_psk.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/pluto_crypt.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/crypt_start_dh.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/build_ke.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/crypt_ke.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/crypt_dh.o

# Local Variables:
# gdb-command: ""
# End Variables:
#
