EXTRAFLAGS+=-I../../libpluto
include ../../libpluto/lp12-parentR2/Makefile
EXTRAFLAGS+=-DSAMPLEDIR=\"${SAMPLEDIR}\"

EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_crypto.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_rsa.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_psk.o
#EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/pluto_crypt.o

# Local Variables:
# gdb-command: ""
# End Variables:
#
