# -*- makefile -*-

SAMPLEDIR=../../libpluto/samples
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}
CONNNAME=parker1--jj2
UNITTEST1ARGS=${WHACKFILE} parker1--jj2 OUTPUT/cryptoR2.pcap parentI1.pcap parentI2.pcap
# purposely use the same conn file as client, it should swap and work.
ENDNAME=parker

TESTNAME=cryptoR2

