# -*- makefile -*-
CONNNAME=bobnet-ikev1
ENDNAME=sun
INPUTPCAPS=v1rwnatM1.pcap v1rwnatM2.pcap v1rwnatM3.pcap
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME} OUTPUT/${TESTNAME}.pcap ${INPUTPCAPS}
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}

TESTNAME=v1rwnatN3

EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev1.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev1_main.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/spdb_v1_struct.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev1_crypto.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/nat_traversal.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/keymgmt.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/x509.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/x509keys.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ac.o

EXTRALIBS+=${LIBPLUTO}

pcapupdate:
	cp ../lp102-v1rwnatM1/OUTPUT/v1rwnatM1.pcap v1rwnatM1.pcap
	cp ../lp104-v1rwnatM2/OUTPUT/v1rwnatM2.pcap v1rwnatM2.pcap
	cp ../lp106-v1rwnatM3/OUTPUT/v1rwnatM3.pcap v1rwnatM3.pcap

