.\"     Title: look
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/14/2008
.\"    Manual: 28 Oct 2006
.\"    Source: 28 Oct 2006
.\"
.TH "LOOK" "8" "11/14/2008" "28 Oct 2006" "28 Oct 2006"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ipsec look - get a quick summary of Openswan status
.SH "SYNOPSIS"
.HP 6
\fBipsec\fR \fIlook\fR
.SH "DESCRIPTION"
.PP
\fILook\fR
is used to get a quick overview of what the status of Openswan is\. It is the equivalent to running the commands
\fIipsec eroute\fR,
\fIipsec spigrp\fR,
\fIipsec tncfg\fR,
\fIipsec spi\fR
and
\fInetstat \-rn\fR\. However a bit of processing is done to combine the outputs\.
.PP
Some of the above commands, and there for
\fIipsec look\fR, are only supported with the KLIPS or MAST stack, and will give errors when used on BSD, Windows or Linux with NETKEY\.
.SH "SEE ALSO"
.PP
\fBipsec\fR(8),
\fBipsec_tncfg\fR(8),
\fBipsec_spi\fR(8),
\fBipsec_spigrp\fR(8),
\fBipsec_eroute\fR(5),
\fBnetstat\fR(8)\.
.SH "HISTORY"
.PP
Man page written for the Linux FreeS/WAN project <\fIhttp://www\.freeswan\.org/\fR> by Michael Richardson\. Original program written by Henry Spencer\.
