# -*- makefile -*-
TESTNAME=rekeyv2nopfs-inCR1
CONNNAME=parker1--jj2--nopfs
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}
UNITTEST1ARGS=-r ${WHACKFILE} ${CONNNAME} /dev/null ../lp10-parentI2/parentR1.pcap ../lp13-parentI3/parentR2.pcap rekeyCR1.pcap
ENDNAME=parker

PCAPDEPENDENCIES = ../lp57-rekeyv2nopfs-R1/OUTPUT/rekeyv2nopfs-R1.pcap
include ../Makefile.pcapupdate

pcapupdate: ${PCAPDEPENDENCIES}
	cp ../lp57-rekeyv2nopfs-R1/OUTPUT/rekeyv2nopfs-R1.pcap rekeyCR1.pcap



