# -*- makefile -*-
TESTNAME=respondselfR1
CONNNAME=gateway--any
ENDNAME=rw
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME} parentI1.pcap OUTPUT/respondselfR1.pcap

pcapupdate:
	cp ../lp14-initiateself/OUTPUT/initiateselfI1.pcap parentI1.pcap
