.\"     Title: _INCLUDE
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/14/2008
.\"    Manual: 25 Apr 2002
.\"    Source: 25 Apr 2002
.\"
.TH "_INCLUDE" "8" "11/14/2008" "25 Apr 2002" "25 Apr 2002"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ipsec _include - internal script to process config files
.SH "DESCRIPTION"
.PP
\fI_include\fR
is used by
\fI_confread\fR
to process
\fBinclude\fR
directives in /etc/ipsec\.conf\.
.SH "SEE ALSO"
.PP
\fBipsec\fR(8),
\fBipsec__confread\fR(8)
.SH "HISTORY"
.PP
Man page written for the Linux FreeS/WAN project <\fIhttp://www\.freeswan\.org/\fR> by Michael Richardson\. Program written by Henry Spencer\.
