include ../lp17-childselfpolicy/Makefile

update_pcaps:
	cp ../lp18-certificateselfI1/OUTPUT/certificateselfI1.pcap  parentI1.pcap
	cp ../lp20-certificateselfI2/OUTPUT/parentI2.pcap  parentI2.pcap


# Local Variables:
# gdb-command: ""
# compile-command: "make clean check"
# End Variables:
#
