# -*- makefile -*-
TESTNAME=certreplyselfR2
CONNNAME=rw
UNITTEST1PCAP=OUTPUT/parentR2.pcap
UNITTEST2PCAP=OUTPUT/parentR2_wrongchildpolicy.pcap
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME} parentI1.pcap parentI2.pcap ${UNITTEST1PCAP}
UNITTEST2ARGS=${WHACKFILE} ${CONNNAME} parentI1.pcap parentI2_wrongchildpolicy.pcap ${UNITTEST2PCAP}
ENDNAME=gatewaycert
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/x509keys.o

# Local Variables:
# gdb-command: ""
# End Variables:
#

