# -*- makefile -*-
CONNNAME=peerA--peerB
ENDNAME=acppeers
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME} peerA-I1.pcap peerA-I2.pcap OUTPUT/${TESTNAME}.pcap

TESTNAME=peerB-R2
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/x509keys.o

PCAPDEPENDENCIES = ../lp121-peerA-I1/OUTPUT/peerA-I1.pcap
PCAPDEPENDENCIES +=../lp123-peerA-I2/OUTPUT/peerA-I2.pcap
include ../Makefile.pcapupdate

pcapupdate: ${PCAPDEPENDENCIES}
	cp ../lp121-peerA-I1/OUTPUT/peerA-I1.pcap .
	cp ../lp123-peerA-I2/OUTPUT/peerA-I2.pcap .

# Local Variables:
# gdb-command: ""
# End Variables:
#

