# -*- makefile -*-
CONNNAME=gateway--any
PCAPOUTPUT=parentI2.pcap
UNITTEST1ARGS=-r ${WHACKFILE} ${CONNNAME} parentR1.pcap      OUTPUT/${PCAPOUTPUT}
ENDNAME=rw

TESTNAME=initiateselfI2

pcapupdate:
	cp ../lp15-respondself/OUTPUT/respondselfR1.pcap parentR1.pcap

