# -*- makefile -*-
CONNNAME=gateway--any
PCAPOUTPUT=initiateselfI2.pcap
UNITTEST1ARGS=-r ${WHACKFILE} ${CONNNAME} OUTPUT/${PCAPOUTPUT} parentR1.pcap
ENDNAME=rw

TESTNAME=initiateselfI2

pcapupdate:
	cp ../lp15-respondself/OUTPUT/respondselfR1.pcap parentR1.pcap

