'\" t
.\"     Title: _REALSETUP
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 10/06/2010
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "_REALSETUP" "8" "10/06/2010" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ipsec__realsetup \- internal routine to start FreeS/WAN\&.
.SH "DESCRIPTION"
.PP
\fI_realsetup\fR
is called by the system init scripts to start the FreeS/WAN system\&. It starts
\fBKLIPS\fR
(the kernel component) and
\fBpluto\fR
(the userspace keying component)\&.
.SH "SEE ALSO"
.PP
\fBipsec\fR(8),
\fBipsec__klipsstart\fR(8),
\fBipsec__plutorun\fR(8)\&.
.SH "HISTORY"
.PP
Man page written for the Linux FreeS/WAN project <\m[blue]\fBhttp://www\&.freeswan\&.org/\fR\m[]> by Michael Richardson\&. Original program by Henry Spencer\&.
