# -*- makefile -*-
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/hostpair.o
SAMPLEDIR=../samples
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}
ENDNAME=moon
CONNNAME=net-net
UNITTESTARGS=${WHACKFILE} ${CONNNAME}

TESTNAME=orientmoon
