# -*- makefile -*-
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev1_main.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/spdb_v1_struct.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev1_crypto.o

CONNNAME=t4901
ENDNAME=h2h-ikev1
UNITTESTARGS=-r ${WHACKFILE} ${CONNNAME}
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}

TESTNAME=parentM1


pcapupdate:
	@true

