CONNNAME=mytunnel-no-ikev1
ENDNAME=h2h
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME} parentM1.pcap OUTPUT/h2hR1.pcap
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}

TESTNAME=h2hR1-deny-ikev1

EXTRALIBS+=${OBJDIRTOP}/programs/pluto/ikev1.o
EXTRALIBS+=${OBJDIRTOP}/programs/pluto/ikev1_main.o
EXTRALIBS+=${OBJDIRTOP}/programs/pluto/spdb_v1_struct.o
EXTRALIBS+=${OBJDIRTOP}/programs/pluto/ikev1_crypto.o

