# -*- makefile -*-
CONNNAME=mytunnel-no-ikev1
ENDNAME=h2h
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME} parentM1.pcap OUTPUT/${TESTNAME}.pcap
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}

TESTNAME=h2hR1-deny-ikev1

EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev1.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev1_main.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/spdb_v1_struct.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev1_crypto.o

EXTRALIBS+=${LIBPLUTO}

pcapupdate:
	cp ../lp43-parentM1/OUTPUT/parentM1.pcap parentM1.pcap


