include ../lp15-respondself/Makefile

PCAPDEPENDENCIES = ../lp43-parentM1/OUTPUT/parentM1.pcap
include ../Makefile.pcapupdate

pcapupdate: ${PCAPDEPENDENCIES}
	cp ../lp43-parentM1/OUTPUT/parentM1.pcap parentM1.pcap


# Local Variables:
# compile: "make clean && make check"
# gdb-command: ""
# End Variables:
#
