# -*- makefile -*-
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/hostpair.o
SAMPLEDIR=../samples
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}
ENDNAME=parker
CONNNAME=parker1--jj2 
UNITTESTARGS=${WHACKFILE} ${CONNNAME}

TESTNAME=orienttest
