TESTNAME=rekey-no-reply-I1
CONNNAME=parker1--jj2
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}
UNITTEST1ARGS=-r ${WHACKFILE} ${CONNNAME} /dev/null ../lp10-parentI2/parentR1.pcap ../lp13-parentI3/parentR2.pcap
ENDNAME=parker

