# -*- makefile -*-
CONNNAME=parker1--jj2
ENDNAME=parker
UNITTEST1ARGS=${WHACKFILE} parker1--jj2 OUTPUT/rekeytwice-CI1.pcap ../lp12-parentR2/parentI1.pcap ../lp12-parentR2/parentI2.pcap rekeyikev2-1-I1.pcap rekeyikev2-2-I1.pcap
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}
TESTNAME=rekeytwice-inCI1

all: check

PCAPDEPENDENCIES = ../lp50-rekey-no-reply-rekey/OUTPUT/rekeyikev2-1-I1.pcap ../lp50-rekey-no-reply-rekey/OUTPUT/rekeyikev2-2-I1.pcap
include ../Makefile.pcapupdate

pcapupdate: ${PCAPDEPENDENCIES}
	cp ../lp50-rekey-no-reply-rekey/OUTPUT/rekeyikev2-1-I1.pcap .
	cp ../lp50-rekey-no-reply-rekey/OUTPUT/rekeyikev2-2-I1.pcap .


