.TH IPSEC 8 "26 March 2002"
.\" RCSID $Id: ipsec.8,v 1.18 2003/02/27 16:51:54 dhr Exp $
.SH NAME
ipsec \- invoke IPsec utilities
.SH SYNOPSIS
.B ipsec
command [ argument ...]
.sp
.B ipsec
.B \-\-help
.br
.B ipsec
.B \-\-version
.br
.B ipsec
.B \-\-versioncode
.br
.B ipsec
.B \-\-copyright
.br
.B ipsec
.B \-\-directory
.br
.B ipsec
.B \-\-confdir
.SH DESCRIPTION
.I Ipsec
invokes any of several utilities involved in controlling the IPsec
encryption/authentication system,
running the specified
.I command
with the specified
.IR argument s
as if it had been invoked directly.
This largely eliminates possible name collisions with other software,
and also permits some centralized services.
.PP
In particular,
.I ipsec
supplies the invoked
.I command
with a suitable PATH environment variable,
and also provides IPSEC_DIR,
IPSEC_CONFS, and IPSEC_VERSION environment variables,
containing respectively
the full pathname of the directory where the IPsec utilities are stored,
the full pathname of the directory where the configuration files live,
and the IPsec version number.
.PP
.B "ipsec \-\-help"
lists the available commands.
Most have their own manual pages, e.g.
.IR ipsec_auto (8)
for
.IR auto .
.PP
.B "ipsec \-\-version"
outputs version information about Linux FreeS/WAN.
A version code of the form ``U\fIxxx\fR/K\fIyyy\fR''
indicates that the user-level utilities are version \fIxxx\fR
but the kernel portion appears to be version \fIyyy\fR
(this form is used only if the two disagree).
.PP
.B "ipsec \-\-versioncode"
outputs \fIjust\fR the version code,
with none of
.BR \-\-version 's
supporting information,
for use by scripts.
.PP
.B "ipsec \-\-copyright"
supplies boring copyright details.
.PP
.B "ipsec \-\-directory"
reports where
.I ipsec
thinks the IPsec utilities are stored.
.PP
.B "ipsec \-\-confdir"
reports where
.I ipsec
thinks the IPsec configuration files are stored.
.SH FILES
/usr/local/lib/ipsec	usual utilities directory
.SH ENVIRONMENT
.PP
The following environment variables control where FreeS/WAN finds its
components.
The
.B ipsec
command sets them if they are not already set.
.nf
.na
IPSEC_EXECDIR	directory containing published commands
IPSEC_LIBDIR	directory containing internal executables
IPSEC_SBINDIR	directory containing \fBipsec\fP command
IPSEC_CONFS	directory containing configuration files
.ad
.fi
.SH SEE ALSO
.hy 0
.na
ipsec.conf(5), ipsec.secrets(5),
ipsec_auto(8),
ipsec_barf(8),
ipsec_setup(8),
ipsec_showdefaults(8),
ipsec_showhostkey(8)
.ad
.hy
.PP
HTML documentation shipped with the release, starting with
.IR doc/index.html .
.I <http://www.freeswan.org/doc.html>
may also be of use.
.SH HISTORY
Written for Linux FreeS/WAN
<http://www.freeswan.org>
by Henry Spencer.
.SH BUGS
The provision of centralized services,
while convenient,
does compromise the original concept of making the utilities
invocable directly as well as via
.IR ipsec .
