'\" t
.\"     Title: IPSEC
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 10/06/2010
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "IPSEC" "8" "10/06/2010" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ipsec \- invoke IPsec utilities
.SH "SYNOPSIS"
.HP \w'\fBipsec\fR\ 'u
\fBipsec\fR \fIcommand\fR [\fIargument\fR...] \fIipsec\fR \-\-help
.br
\fIipsec\fR \-\-version
.br
\fIipsec\fR \-\-versioncode
.br
\fIipsec\fR \-\-copyright
.br
\fIipsec\fR \-\-directory
.br
\fIipsec\fR \-\-confdir
.SH "DESCRIPTION"
.PP
\fIIpsec\fR
invokes any of several utilities involved in controlling the IPsec encryption/authentication system, running the specified
\fIcommand\fR
with the specified
\fIargument\fRs as if it had been invoked directly\&. This largely eliminates possible name collisions with other software, and also permits some centralized services\&.
.PP
In particular,
\fBipsec\fR
supplies the invoked
\fIcommand\fR
with a suitable PATH environment variable, and also provides IPSEC_DIR, IPSEC_CONFS, and IPSEC_VERSION environment variables, containing respectively the full pathname of the directory where the IPsec utilities are stored, the full pathname of the directory where the configuration files live, and the IPsec version number\&.
.PP
\fBipsec \-\-help\fR
lists the available commands\&. Most have their own manual pages, e\&.g\&.
\fBipsec_auto\fR(8)
for
\fIauto\fR\&.
.PP
\fBipsec \-\-version\fR
outputs version information about Linux FreeS/WAN\&. A version code of the form ``U\fIxxx\fR/K\fIyyy\fR\'\' indicates that the user\-level utilities are version
\fIxxx\fR
but the kernel portion appears to be version
\fIyyy\fR
(this form is used only if the two disagree)\&.
.PP
\fBipsec \-\-versioncode\fR
outputs
\fIjust\fR
the version code, with none of
\fB\-\-version\fR\'s supporting information, for use by scripts\&.
.PP
\fBipsec \-\-copyright\fR
supplies boring copyright details\&.
.PP
\fBipsec \-\-directory\fR
reports where
\fBipsec\fR
thinks the IPsec utilities are stored\&.
.PP
\fBipsec \-\-confdir\fR
reports where
\fBipsec\fR
thinks the IPsec configuration files are stored\&.
.SH "FILES"
.PP
/usr/local/lib/ipsec usual utilities directory
.SH "ENVIRONMENT"
.PP
The following environment variables control where FreeS/WAN finds its components\&. The
\fBipsec\fR
command sets them if they are not already set\&.
.sp
.if n \{\
.RS 4
.\}
.nf

IPSEC_EXECDIR	directory containing published commands
IPSEC_LIBDIR	directory containing internal executables
IPSEC_SBINDIR	directory containing \fBipsec\fR command
IPSEC_CONFS	directory containing configuration files

.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
ipsec\&.\fBconf\fR(5), ipsec\&.\fBsecrets\fR(5),
\fBipsec_auto\fR(8),
\fBipsec_barf\fR(8),
\fBipsec_setup\fR(8),
\fBipsec_showdefaults\fR(8),
\fBipsec_showhostkey\fR(8)
.PP
HTML documentation shipped with the release, starting with
\fIdoc/index\&.html\fR\&.
\fI<\fR\fI\m[blue]\fBhttp://www\&.freeswan\&.org/doc\&.html\fR\m[]\fR\fI>\fR
may also be of use\&.
.SH "HISTORY"
.PP
Written for Linux FreeS/WAN <\m[blue]\fBhttp://www\&.freeswan\&.org\fR\m[]> by Henry Spencer\&.
.SH "BUGS"
.PP
The provision of centralized services, while convenient, does compromise the original concept of making the utilities invocable directly as well as via
\fBipsec\fR\&.
