.\"     Title: IPSEC_MANUAL
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/14/2008
.\"    Manual: 17 July 2001
.\"    Source: 17 July 2001
.\"
.TH "IPSEC_MANUAL" "8" "11/14/2008" "17 July 2001" "17 July 2001"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ipsec manual - take manually-keyed IPsec connections up and down
.SH "SYNOPSIS"
.HP 6
\fBipsec\fR \fImanual\fR [\-\-show] [\-\-showonly] [\-\-other] [\-\-iam\ \fIaddress@interface\fR] [\-\-config\ \fIconfigfile\fR] \fIoperation\fR
.HP 6
\fBipsec\fR \fImanual\fR [\fIoptions\fR] \-\-union \fIoperation_part\fR...
.SH "DESCRIPTION"
.PP
This command was obsoleted around the same time that Al Gore invented the internet\.
.PP
During the jurassic period it was used to manipulates manually\-keyed Openswan IPsec connections, setting them up and shutting them down, based on the information in the IPsec configuration file\. Normally, manually keyed connections should not be used \- automatic keying connections
.PP
There are no rational reasons to use this, and it is not supported anymore\.
