.\"     Title: IPSEC_TRAP_SENDCOUNT
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/14/2008
.\"    Manual: 19 Jun 2003
.\"    Source: 19 Jun 2003
.\"
.TH "IPSEC_TRAP_SENDCOUNT" "5" "11/14/2008" "19 Jun 2003" "19 Jun 2003"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
trap_sendcount - KLIPS statistic on number of successful ACQUIREs
.SH "SYNOPSIS"
.HP 4
\fBcat\fR \fI/proc/net/ipsec/stats/trap_sendcount\fR
.SH "OBSOLETE"
.PP
Note that trap_sendcount is only supported on the classic KLIPS stack\. It is not supported on any other stack and will be completely removed in future versions\. A replacement command still needs to be designed
.SH "DESCRIPTION"
.PP
\fI/proc/net/ipsec/stats/trap_sendcount\fR
is a read\-only file\. It contains a hexadecimal number which records the number of successful PF_ACQUIRE messages that were sent\.
.SH "FILES"
.PP
/proc/net/ipsec/stats/trap_sendcount
.SH "SEE ALSO"
.PP
\fBipsec\fR(8),
\fBipsec_pf_key\fR(5),
\fBtrap_count\fR(5),
\fBpluto\fR(8)
.SH "HISTORY"
.PP
Written for the Linux FreeS/WAN project <\fIhttp://www\.freeswan\.org/\fR> by Michael C\. Richardson <mcr@freeswan\.org>
