'\" t
.\"     Title: IPSEC_IKEPING
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.74.3 <http://docbook.sf.net/>
.\"      Date: 07/08/2009
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "IPSEC_IKEPING" "8" "07/08/2009" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ipsec_ikeping \- send/receive ISAKMP/IKE echo requests/replies
.SH "SYNOPSIS"
.HP \w'\fBipsec\fR\ 'u
\fBipsec\fR \fIikeping\fR [\-\-listen] [\-\-verbose] [\-\-wait\ \fItime\fR] [\-\-exchangenum\ \fInum\fR] [\-\-ikeport\ \fIlocalport\fR] [\-\-ikeaddress\ \fIaddress\fR] [\-\-inet] [\-\-inet6] \fIdestaddr\fR [\fI/dstport\fR...]
.SH "DESCRIPTION"
.PP
\fIIkeping\fR
sends and receives ISAKMP/IKE echo request and echo reply packets\&. These packets are intended for diagnostics purposes, in a manner similar to
\fBping\fR(8)
does for ICMP echo request/reply packets\&.
.PP
At the time of this writing, the ISAKMP echo request/reply exchange is still an internet\-draft (draft\-richardson\-ipsec\-ikeping\-00), and is therefore completely non\-standard\&. The Openswan IKE daemon pluto does implement this draft, so ikeping can be used to test connectivity to an openswan ipsec server\&.
.PP
\fIIkeping\fR
will bind to the local address given by
\fB\-\-ikeaddress\fR
and the port number given by
\fB\-\-ikeport\fR
defaulting to the wildcard address and the ISAKMP port 500\&. An ISAKMP exchange of type 244 (a private use number) is sent to each of the address/ports listed on the command line\&. The exchange number may be overridden by the
\fB\-\-exchangenum\fR
option\&.
.PP
\fIIkeping\fR
then listens for replies, printing them as they are received\&. Replies are of exchange type 245 or the specified exchange number plus 1\&.
\fIIkeping\fR
will keep listening until it either receives as many echo responses as it sent, or until the timeout period (5 seconds) has been reached\&. Receipt of a packet will reset the timer\&. The
\fB\-\-wait\fR
option can be used to specify a different timeout period\&.
.PP
If the
\fB\-\-listen\fR
option is given, then
\fIikeping\fR
will not send any packets\&. Instead, it will listen for them and reply to each request received\&.
.PP
If the
\fB\-\-natt\fR
option is given, then
\fIikeping\fR
will set the socket to permit UDP encapsulated ESP packets\&. This is only useful in listen mode\&.
.SH "FILES"
.PP
no external files
.SH "SEE ALSO"
.PP
\fBping\fR(8),
\fBipsec_pluto\fR(8)
.SH "HISTORY"
.PP
Written for the Linux FreeS/WAN project <\m[blue]\fBhttp://www\&.freeswan\&.org\fR\m[]> by Michael Richardson\&.
