# -*- makefile -*-
TESTNAME=certreplydaveR2
CONNNAME1=rw-any
CONNNAME=${CONNNAME1} rw-carol rw-dave
#UNITTEST1PCAP=OUTPUT/parentR1dave.pcap
UNITTEST1PCAP=OUTPUT/parentR2dave.pcap
#UNITTEST1ARGS=${WHACKFILE} ${CONNNAME1} ${UNITTEST1PCAP} carolI1.pcap carolI2.pcap davecertI1.pcap
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME1} ${UNITTEST1PCAP} carolI1.pcap carolI2.pcap davecertI1.pcap davecertI2.pcap
ENDNAME=gatewaycert
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/x509keys.o

PCAPDEPENDENCIES = ../lp18-certificateselfI1/OUTPUT/certificateselfI1.pcap ../lp20-certificateselfI2/OUTPUT/parentI2.pcap ../lp23-davecertI1/OUTPUT/davecertI1.pcap ../lp26-davecertI2/OUTPUT/parentI2.pcap
include ../Makefile.pcapupdate

pcapupdate: ${PCAPDEPENDENCIES}
	cp ../lp18-certificateselfI1/OUTPUT/certificateselfI1.pcap carolI1.pcap
	cp ../lp20-certificateselfI2/OUTPUT/parentI2.pcap          carolI2.pcap
	cp ../lp23-davecertI1/OUTPUT/davecertI1.pcap               davecertI1.pcap
	cp ../lp26-davecertI2/OUTPUT/parentI2.pcap                 davecertI2.pcap

# Local Variables:
# gdb-command: ""
# End Variables:
#

