# -*- makefile -*-
TESTNAME=certreplydaveR2
CONNNAME1=rw-any
CONNNAME=${CONNNAME1} rw-carol rw-dave
#UNITTEST1PCAP=OUTPUT/parentR1dave.pcap
UNITTEST1PCAP=OUTPUT/parentR2dave.pcap
#UNITTEST1ARGS=${WHACKFILE} ${CONNNAME1} ${UNITTEST1PCAP} carolI1.pcap carolI2.pcap davecertI1.pcap
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME1} ${UNITTEST1PCAP} carolI1.pcap carolI2.pcap davecertI1.pcap davecertI2.pcap
ENDNAME=gatewaycert
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/x509keys.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/hostpair.o

# Local Variables:
# gdb-command: ""
# End Variables:
#

