'\" t
.\"     Title: IPSEC_EROUTE
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 02/25/2010
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "IPSEC_EROUTE" "5" "02/25/2010" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ipsec_eroute \- list of existing eroutes
.SH "SYNOPSIS"
.HP \w'\fBipsec\fR\ 'u
\fBipsec\fR \fIeroute\fR
.br
\fIcat/proc/net/ipsec_eroute\fR
.SH "OBSOLETE"
.PP
Note that eroute is only supported on the classic KLIPS stack\&. It is not supported on any other stack and will be completely removed in future versions\&. A replacement command still needs to be designed
.SH "DESCRIPTION"
.PP
/proc/net/ipsec_eroute
lists the IPSEC extended routing tables, which control what (if any) processing is applied to non\-encrypted packets arriving for IPSEC processing and forwarding\&. At this point it is a read\-only file\&.
.PP
A table entry consists of:
.PP
+
.RS 4
packet count,
.RE
.PP
+
.RS 4
source address with mask and source port (0 if all ports or not applicable)
.RE
.PP
+
.RS 4
a \'\->\' separator for visual and automated parsing between src and dst
.RE
.PP
+
.RS 4
destination address with mask and destination port (0 if all ports or not applicable)
.RE
.PP
+
.RS 4
a \'=>\' separator for visual and automated parsing between selection criteria and SAID to use
.RE
.PP
+
.RS 4
SAID (Security Association IDentifier), comprised of:
.RE
.PP
+
.RS 4
protocol (\fIproto\fR),
.RE
.PP
+
.RS 4
address family (\fIaf\fR), where \'\&.\' stands for IPv4 and \':\' for IPv6
.RE
.PP
+
.RS 4
Security Parameters Index (\fISPI\fR),
.RE
.PP
+
.RS 4
effective destination (\fIedst\fR), where the packet should be forwarded after processing (normally the other security gateway) together indicate which Security Association should be used to process the packet,
.RE
.PP
+
.RS 4
a \':\' separating the SAID from the transport protocol (0 if all protocols)
.RE
.PP
+
.RS 4
source identity text string with no whitespace, in parens,
.RE
.PP
+
.RS 4
destination identity text string with no whitespace, in parens
.RE
.PP
Addresses are written as IPv4 dotted quads or IPv6 coloned hex, protocol is one of "ah", "esp", "comp" or "tun" and SPIs are prefixed hexadecimal numbers where the prefix \'\&.\' is for IPv4 and the prefix \':\' is for IPv6
.PP
SAIDs are written as "protoafSPI@edst"\&. There are also 5 "magic" SAIDs which have special meaning:
.PP
+
.RS 4
\fB%drop\fR
means that matches are to be dropped
.RE
.PP
+
.RS 4
\fB%reject\fR
means that matches are to be dropped and an ICMP returned, if possible to inform
.RE
.PP
+
.RS 4
\fB%trap\fR
means that matches are to trigger an ACQUIRE message to the Key Management daemon(s) and a hold eroute will be put in place to prevent subsequent packets also triggering ACQUIRE messages\&.
.RE
.PP
+
.RS 4
\fB%hold\fR
means that matches are to stored until the eroute is replaced or until that eroute gets reaped
.RE
.PP
+
.RS 4
\fB%pass\fR
means that matches are to allowed to pass without IPSEC processing
.RE
.SH "EXAMPLES"
.PP
\fB1867 172\&.31\&.252\&.0/24:0 \-> 0\&.0\&.0\&.0/0:0 => tun0x130@192\&.168\&.43\&.1:0 \fR

\fB () ()\fR
.PP
means that 1,867 packets have been sent to an
\fBeroute\fR
that has been set up to protect traffic between the subnet
172\&.31\&.252\&.0
with a subnet mask of
24
bits and the default address/mask represented by an address of
0\&.0\&.0\&.0
with a subnet mask of
0
bits using the local machine as a security gateway on this end of the tunnel and the machine
192\&.168\&.43\&.1
on the other end of the tunnel with a Security Association IDentifier of
\fBtun0x130@192\&.168\&.43\&.1\fR
which means that it is a tunnel mode connection (4, IPPROTO_IPIP) with a Security Parameters Index of
130
in hexadecimal with no identies defined for either end\&.
.PP
\fB746 192\&.168\&.2\&.110/32:0 \-> 192\&.168\&.2\&.120/32:25 => esp0x130@192\&.168\&.2\&.120:6 \fR

\fB () ()\fR
.PP
means that 746 packets have been sent to an
\fBeroute\fR
that has been set up to protect traffic sent from any port on the host
192\&.168\&.2\&.110
to the SMTP (TCP, port 25) port on the host
192\&.168\&.2\&.120
with a Security Association IDentifier of
\fBtun0x130@192\&.168\&.2\&.120\fR
which means that it is a transport mode connection with a Security Parameters Index of
130
in hexadecimal with no identies defined for either end\&.
.PP
\fB125 3049:1::/64 \-> 0:0/0 => tun:130@3058:4::5 () ()\fR
.PP
means that 125 packets have been sent to an
\fBeroute\fR
that has been set up to protect traffic between the subnet
\fB3049:1::\fR
with a subnet mask of
64
bits and the default address/mask represented by an address of
\fB0:0\fR
with a subnet mask of
0
bits using the local machine as a security gateway on this end of the tunnel and the machine
\fB3058:4::5\fR
on the other end of the tunnel with a Security Association IDentifier of
\fBtun:130@3058:4::5\fR
which means that it is a tunnel mode connection with a Security Parameters Index of
130
in hexadecimal with no identies defined for either end\&.
.PP
\fB42 192\&.168\&.6\&.0/24:0 \-> 192\&.168\&.7\&.0/24:0 => %passthrough\fR
.PP
means that 42 packets have been sent to an
\fBeroute\fR
that has been set up to pass the traffic from the subnet
192\&.168\&.6\&.0
with a subnet mask of
24
bits and to subnet
192\&.168\&.7\&.0
with a subnet mask of
24
bits without any IPSEC processing with no identies defined for either end\&.
.PP
\fB2112 192\&.168\&.8\&.55/32:0 \-> 192\&.168\&.9\&.47/24:0 => %hold (east) ()\fR
.PP
means that 2112 packets have been sent to an
\fBeroute\fR
that has been set up to hold the traffic from the host
192\&.168\&.8\&.55
and to host
192\&.168\&.9\&.47
until a key exchange from a Key Management daemon succeeds and puts in an SA or fails and puts in a pass or drop eroute depending on the default configuration with the local client defined as "east" and no identy defined for the remote end\&.
.PP
\fB2001 192\&.168\&.2\&.110/32:0 \-> 192\&.168\&.2\&.120/32:0 => \fR

\fB esp0xe6de@192\&.168\&.2\&.120:0 () ()\fR
.PP
means that 2001 packets have been sent to an
\fBeroute\fR
that has been set up to protect traffic between the host
192\&.168\&.2\&.110
and the host
192\&.168\&.2\&.120
using
192\&.168\&.2\&.110
as a security gateway on this end of the connection and the machine
192\&.168\&.2\&.120
on the other end of the connection with a Security Association IDentifier of
\fBesp0xe6de@192\&.168\&.2\&.120\fR
which means that it is a transport mode connection with a Security Parameters Index of
\fBe6de\fR
in hexadecimal using Encapsuation Security Payload protocol (50, IPPROTO_ESP) with no identies defined for either end\&.
.PP
\fB1984 3049:1::110/128 \-> 3049:1::120/128 => \fR

\fB ah:f5ed@3049:1::120 () ()\fR
.PP
means that 1984 packets have been sent to an
\fBeroute\fR
that has been set up to authenticate traffic between the host
\fB3049:1::110\fR
and the host
\fB3049:1::120\fR
using
\fB3049:1::110\fR
as a security gateway on this end of the connection and the machine
\fB3049:1::120\fR
on the other end of the connection with a Security Association IDentifier of
\fBah:f5ed@3049:1::120\fR
which means that it is a transport mode connection with a Security Parameters Index of
\fBf5ed\fR
in hexadecimal using Authentication Header protocol (51, IPPROTO_AH) with no identies defined for either end\&.
.SH "FILES"
.PP
/proc/net/ipsec_eroute, /usr/local/bin/ipsec
.SH "SEE ALSO"
.PP
ipsec(8), ipsec_manual(8), ipsec_tncfg(5), ipsec_spi(5), ipsec_spigrp(5), ipsec_klipsdebug(5), ipsec_eroute(8), ipsec_version(5), ipsec_pf_key(5)
.SH "HISTORY"
.PP
Written for the Linux FreeS/WAN project <\m[blue]\fBhttp://www\&.freeswan\&.org/\fR\m[]> by Richard Guy Briggs\&.
