# -*- makefile -*-
TESTNAME=xf12-parentR2

SAMPLEDIR=../../libpluto/samples
CONNNAME=parker1--jj2
ENDNAME=parker
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}

EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_crypto.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_rsa.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_psk.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/kernel.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/kernel_forces.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/signatures.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/keymgmt.o

# /dev/null is output pcap, as there is none.
UNITTEST1ARGS=-r ${WHACKFILE} ${CONNNAME} OUTPUT/${TESTNAME}.pcap parentI1.pcap parentI2.pcap

pcapupdate:
	cp ../../libpluto/lp02-parentI1/OUTPUT/parentI1.pcap parentI1.pcap
	cp ../../ikev2crypto/ct10-parentI2/OUTPUT/cryptoI2.pcap parentI2.pcap





