EXTRAFLAGS+=-I..
EXTRAFLAGS+=-I../../libpluto
EXTRAFLAGS+=-I../../libpluto/lp02-parentI1
include ../../libpluto/lp02-parentI1/Makefile
EXTRAFLAGS+=-DSAMPLEDIR=\"${SAMPLEDIR}\"

# Local Variables:
# gdb-command: ""
# End Variables:
#
