EXTRAFLAGS+=-I..
EXTRAFLAGS+=-I../../libpluto
EXTRAFLAGS+=-I../../libpluto/lp02-parentI1
include ../../libpluto/lp02-parentI1/Makefile
EXTRAFLAGS+=-DSAMPLEDIR=\"${SAMPLEDIR}\"

EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/keys.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_crypto.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_rsa.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev2_psk.o

# Local Variables:
# gdb-command: ""
# End Variables:
#
