'\" t
.\"     Title: IPSEC_KLIPSDEBUG
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 02/25/2010
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "IPSEC_KLIPSDEBUG" "5" "02/25/2010" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ipsec_klipsdebug \- list KLIPS (kernel IPSEC support) debug features and level
.SH "SYNOPSIS"
.HP \w'\fBipsec\fR\ 'u
\fBipsec\fR \fIklipsdebug\fR
.br
\fIcat/proc/net/ipsec_klipsdebug\fR
.SH "DESCRIPTION"
.PP
/proc/net/ipsec_klipsdebug
lists flags that control various parts of the debugging output of KLIPS and MAST, two of the IPsec stacks supported by Openswan\&. At this point it is a read\-only file\&.
.PP
A table entry consists of:
.PP
+
.RS 4
a KLIPS debug variable
.RE
.PP
+
.RS 4
a \'=\' separator for visual and automated parsing between the variable name and its current value
.RE
.PP
+
.RS 4
hexadecimal bitmap of variable\'s flags\&.
.RE
.PP
The variable names roughly describe the scope of the debugging variable\&. Currently, no flags are documented or individually accessible yet except tunnel\-xmit\&.
.PP
The variable names are:
.PP
\fBtunnel\fR
.RS 4
tunnelling code
.RE
.PP
\fBnetlink\fR
.RS 4
userspace communication code (obsolete)
.RE
.PP
\fBxform\fR
.RS 4
transform selection and manipulation code
.RE
.PP
\fBeroute\fR
.RS 4
eroute table manipulation code
.RE
.PP
\fBspi\fR
.RS 4
SA table manipulation code
.RE
.PP
\fBradij\fR
.RS 4
radij tree manipulation code
.RE
.PP
\fBesp\fR
.RS 4
encryptions transforms code
.RE
.PP
\fBah\fR
.RS 4
authentication transforms code
.RE
.PP
\fBrcv\fR
.RS 4
receive code
.RE
.PP
\fBipcomp\fR
.RS 4
ip compression transforms code
.RE
.PP
\fBverbose\fR
.RS 4
give even more information, beware this will probably trample the 4k kernel printk buffer giving inaccurate output
.RE
.PP
All KLIPS debug output appears as
\fBkernel\&.info\fR
messages to
\fBsyslogd\fR(8)\&. Most systems are set up to log these messages to
/var/log/messages\&.
.SH "EXAMPLES"
.PP
\fBdebug_tunnel=00000010\&.\fR

\fBdebug_netlink=00000000\&.\fR

\fBdebug_xform=00000000\&.\fR

\fBdebug_eroute=00000000\&.\fR

\fBdebug_spi=00000000\&.\fR

\fBdebug_radij=00000000\&.\fR

\fBdebug_esp=00000000\&.\fR

\fBdebug_ah=00000000\&.\fR

\fBdebug_rcv=00000000\&.\fR

\fBdebug_pfkey=ffffffff\&.\fR
.PP
means that one
\fBtunnel\fR
flag has been set (tunnel\-xmit), full
\fBpfkey\fR
sockets debugging has been set and everything else is not set\&.
.SH "FILES"
.PP
/proc/net/ipsec_klipsdebug, /usr/local/bin/ipsec
.SH "SEE ALSO"
.PP
ipsec(8), ipsec_manual(8), ipsec_tncfg(8), ipsec_eroute(8), ipsec_spi(8), ipsec_spigrp(8), ipsec_klipsdebug(5), ipsec_version(5), ipsec_pf_key(5)
.SH "HISTORY"
.PP
Written for the Linux FreeS/WAN project <\m[blue]\fBhttp://www\&.freeswan\&.org/\fR\m[]> by Richard Guy Briggs\&.
