'\" t
.\"     Title: IPSEC_KLIPSDEBUG
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 10/06/2010
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "IPSEC_KLIPSDEBUG" "8" "10/06/2010" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ipsec_klipsdebug \- set KLIPS and MAST debug features and level\&. Other stacks are not supported\&.
.SH "SYNOPSIS"
.HP \w'\fBipsec\fR\ 'u
\fBipsec\fR \fIklipsdebug\fR
.br
\fIipsec\ klipsdebug\fR \-\-set \fIflagname\fR
.br
\fIipsec\ klipsdebug\fR \-\-clear \fIflagname\fR
.br
\fIipsec\ klipsdebug\fR \-\-all
.br
\fIipsec\ klipsdebug\fR \-\-none
.br
\fIipsec\ klipsdebug\fR \-\-help
.br
\fIipsec\ klipsdebug\fR \-\-version
.SH "DESCRIPTION"
.PP
\fIKlipsdebug\fR
sets and clears flags that control various parts of the debugging output of Klips (the kernel portion of FreeS/WAN IPSEC)\&. The form with no additional arguments lists the present contents of /proc/net/ipsec_klipsdebug\&. The
\fB\-\-set\fR
form turns the specified flag on, while the
\fB\-\-clear\fR
form turns the specified flag off\&. The
\fB\-\-all\fR
form turns all flags on except verbose, while the
\fB\-\-none\fR
form turns all flags off\&.
.PP
The current flag names are:
.PP
\fBtunnel\fR
.RS 4
tunnelling code
.RE
.PP
\fBtunnel\-xmit\fR
.RS 4
tunnelling transmit only code
.RE
.PP
\fBpfkey\fR
.RS 4
userspace communication code
.RE
.PP
\fBxform\fR
.RS 4
transform selection and manipulation code
.RE
.PP
\fBeroute\fR
.RS 4
eroute table manipulation code
.RE
.PP
\fBspi\fR
.RS 4
SA table manipulation code
.RE
.PP
\fBradij\fR
.RS 4
radij tree manipulation code
.RE
.PP
\fBesp\fR
.RS 4
encryptions transforms code
.RE
.PP
\fBah\fR
.RS 4
authentication transforms code
\fBrcv\fR
receive code
.RE
.PP
\fBipcomp\fR
.RS 4
ip compression transforms code
.RE
.PP
\fBverbose\fR
.RS 4
give even more information, BEWARE: a)this will print authentication and encryption keys in the logs b)this will probably trample the 4k kernel printk buffer giving inaccurate output
.RE
.PP
All Klips debug output appears as
\fBkernel\&.info\fR
messages to
\fBsyslogd\fR(8)\&. Most systems are set up to log these messages to
/var/log/messages\&. Beware that
\fBklipsdebug\fR
\fB\-\-all\fR
produces a lot of output and the log file will grow quickly\&.
.PP
The file format for /proc/net/ipsec_klipsdebug is discussed in ipsec_klipsdebug(5)\&.
.SH "EXAMPLES"
.PP
\fBklipsdebug \-\-all\fR
.RS 4
turns on all KLIPS debugging except verbose\&.
.RE
.PP
\fBklipsdebug \-\-clear tunnel\fR
.RS 4
turns off only the
\fBtunnel\fR
debugging messages\&.
.RE
.SH "FILES"
.PP
/proc/net/ipsec_klipsdebug, /usr/local/bin/ipsec
.SH "SEE ALSO"
.PP
ipsec(8), ipsec_manual(8), ipsec_tncfg(8), ipsec_eroute(8), ipsec_spi(8), ipsec_spigrp(8), ipsec_klipsdebug(5)
.SH "HISTORY"
.PP
Written for the Linux FreeS/WAN project <\m[blue]\fBhttp://www\&.freeswan\&.org/\fR\m[]> by Richard Guy Briggs\&.
.SH "BUGS"
.PP
It really ought to be possible to set or unset selective combinations of flags\&.
