# -*- makefile -*-
CONNNAME=t4901
ENDNAME=h2h-ikev1
INPUTPCAPS=parentM1.pcap parentM2.pcap parentM3.pcap
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME} OUTPUT/${TESTNAME}.pcap ${INPUTPCAPS}
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}

TESTNAME=parentN3

EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev1.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev1_main.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/spdb_v1_struct.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/ikev1_crypto.o
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/nat_traversal.o

EXTRALIBS+=${LIBPLUTO}

pcapupdate:
	cp ../lp43-parentM1/OUTPUT/parentM1.pcap parentM1.pcap
	cp ../lp74-parentM2/OUTPUT/parentM2.pcap parentM2.pcap
	cp ../lp76-parentM3/OUTPUT/parentM3.pcap parentM3.pcap
