# -*- makefile -*-
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}
TESTNAME=parentI2
CONNNAME=parker1--jj2
ENDNAME=parker
UNITTEST1ARGS=-r ${WHACKFILE} ${CONNNAME} OUTPUT/${TESTNAME}.pcap parentR1.pcap

PCAPDEPENDENCIES = ../lp08-parentR1/OUTPUT/parentR1.pcap
include ../Makefile.pcapupdate

pcapupdate: ${PCAPDEPENDENCIES}
	cp ../lp08-parentR1/OUTPUT/parentR1.pcap .
