.\"     Title: ipsec addconn
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/14/2008
.\"    Manual: 7 Mar 2006
.\"    Source: 7 Mar 2006
.\"
.TH "IPSEC_ADDCONN" "8" "11/14/2008" "7 Mar 2006" "7 Mar 2006"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ipsec_addconn \- load a given policy into pluto
.SH "DESCRIPTION"
.PP
\fIipsec addconn\fR
This documentation should be written by Paul\.
.SH "HISTORY"
.PP
Man page written for the Xelerance Openswan project <\fIhttp://www\.openswan\.org/\fR> by Michael Richardson\.
