# ipsec starter Makefile
# Copyright (C) 2001 Mathieu Lafon - Arkoon Network Security
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.  See <http://www.fsf.org/copyleft/gpl.txt>.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

$(info info: addcon/Makefile: MAKECMDGOALS="$(MAKECMDGOALS)")

LIBRESWANSRCDIR?=$(shell cd ../..; pwd)
include ${LIBRESWANSRCDIR}/Makefile.inc

PROGLIBS=${WHACKLIB} ${IPSECCONFLIB} 
#EXTRALIBS=-lefence

PROGRAM=addconn

# reach into pluto for now.
INCLUDES=-I${LIBRESWANSRCDIR}/programs/pluto
INCLUDES+=-I${srcdir}

include ${srcdir}../Makefile.program

TAGS:	$(DISTSRC)
	LC_ALL=C etags $(ETAGSFLAGS) $(DISTSRC) $(LIBLIBRESWANDIR)/*.[ch]

