# -*- makefile -*-

TESTNAME=parentR2anychoice
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}

CONNNAME=any1--jj2 maryjane1--jj2
ENDNAME=parker
UNITTEST1ARGS=${WHACKFILE} any1--jj2 OUTPUT/${TESTNAME}.pcap parentI1.pcap parentI2.pcap

pcapupdate:
	cp ../lp02-parentI1/OUTPUT/parentI1.pcap parentI1.pcap
	cp ../lp10-parentI2/OUTPUT/parentI2.pcap parentI2.pcap



