whack-message = {
  WHACK_STATUS     => StatusOptions,
  WHACK_SHUTDOWN   => { },
  WHACK_OPTIONS    => OptionsCommand,
  WHACK_CONNECTION => Connection,
  WHACK_ROUTE      => { WHACK_OPT_NAME=> tstr },
  WHACK_UNROUTE    => { WHACK_OPT_NAME=> tstr },
  WHACK_INITIATE   => { WHACK_OPT_NAME=> tstr },
  WHACK_INITIATE_OPPO=> InitiateOppo,
  WHACK_TERMINATE  => { WHACK_OPT_NAME=> tstr },
  WHACK_ADD_KEY    => PublicKey,
  WHACK_DELETE     => tstr,
  WHACK_LISTEN     => 1,
  WHACK_UNLISTEN   => 1,
  WHACK_LIST       => uint,
  WHACK_PURGE_OCSP => uint,
  WHACK_REREAD     => uint,
  WHACK_MYID       => tstr,
  WHACK_DELETESTATE=> uint,
  WHACK_CRASHPEER  => IPaddress,
  WHACK_ASYNC      => uint,
  WHACK_NOOP       => {},
}

StatusOptions = {
  WHACK_STAT_OPTIONS => bool,
  WHACK_STAT_ALGORITHMS => bool,
  WHACK_STAT_JSON => bool,
  WHACK_STAT_POLICY => bool,
  WHACK_STAT_STATES => bool
}
WHACK_STAT_OPTIONS    = 1
WHACK_STAT_ALGORITHMS = 2
WHACK_STAT_JSON       = 3
WHACK_STAT_POLICY     = 4
WHACK_STAT_STATES     = 5


PublicKey = {
  WHACK_OPT_KEYID=>  tstr,
  WHACK_OPT_KEYALG=> uint,
  WHACK_OPT_KEYVAL=> bstr,
}

Connection = {
  WHACK_OPT_NAME=>  tstr,
  WHACK_OPT_LEFT=> ConnectionEnd,
  WHACK_OPT_RIGHT=>ConnectionEnd,
  WHACK_OPT_CONNALIAS=> tstr,
  WHACK_OPT_IKE=>  tstr,
  WHACK_OPT_ESP=>  tstr,
  WHACK_OPT_POLICYLABEL=> tstr,
  WHACK_OPT_DPD_DELAY=>   uint,
  WHACK_OPT_DPD_TIMEOUT=> uint,
  WHACK_OPT_DPD_ACTION=>  uint,
  WHACK_OPT_DPD_COUNT=>   uint,
  WHACK_OPT_POLICY=>      uint,
  WHACK_OPT_LIFETIME_IKE=> uint,
  WHACK_OPT_LIFETIME_IPSEC=> uint,
  WHACK_OPT_LIFETIME_REKEY_MARGIN=> uint,
  WHACK_OPT_LIFETIME_REKEY_FUZZ=>   uint,
  WHACK_OPT_LIFETIME_REKEY_TRIES=>  uint,
  WHACK_OPT_END_ADDR_FAMILY=> uint,
}

ConnectionEnd = {
  WHACK_OPT_END_ID=> tstr,
  WHACK_OPT_END_CERT=> tstr,
  WHACK_OPT_END_CA=> tstr,
  WHACK_OPT_END_GROUPS=> tstr,
  WHACK_OPT_END_VIRT=> tstr,
  WHACK_OPT_END_XAUTH_NAME=> tstr,
  WHACK_OPT_END_HOST_ADDRNAME=> tstr,
  WHACK_OPT_HOST_TYPE=> uint,
  WHACK_OPT_END_HOST_ADDR=> IPaddress,
  WHACK_OPT_KEYTYPE=> uint,
  WHACK_OPT_HAS_CLIENT=> uint,
  WHACK_OPT_HAS_CLIENT_WILDCARD=> uint,
  WHACK_OPT_HAS_PORT_WILDCARD=>   uint,
  WHACK_OPT_HOST_PORT=> uint,
  WHACK_OPT_PORT=> uint,
  WHACK_OPT_XAUTH_SERVER=> uint,
  WHACK_OPT_XAUTH_CLIENT=> uint,
  WHACK_OPT_MODECFG_SERVER=> uint,
  WHACK_OPT_MODECFG_CLIENT=> uint,
  WHACK_OPT_CERTPOLICY=> uint,
  WHACK_OPT_CERTTYPE=>   uint,
  WHACK_OPT_TUNDEV=>     uint,
  WHACK_OPT_END_HOST_NEXTHOP=> IPaddress,
  WHACK_OPT_END_HOST_SRCIP=> IPaddress,
  WHACK_OPT_END_CLIENT=> IPsubnet,
}

OptionsCommand = {
  WHACK_OPT_COREDIR=>   tstr,
  WHACK_OPT_NHELPERS=> uint,
  WHACK_OPT_SECCTX=>    uint,
  WHACK_OPT_FORKDESIRED=> bool,
  WHACK_OPT_STDERR_DESIRED=> bool,
  WHACK_OPT_LOG_WITH_TIMESTAMP=> bool,
  WHACK_OPT_KERN_INTERFACE=> uint,
  WHACK_OPT_SET_DEBUGGING=>  uint,
  WHACK_OPT_LISTENADDR=>     tstr,
  WHACK_OPT_ADD_DEBUGGING=>  uint,
  WHACK_OPT_SAME_ADDR_OK=>   bool,
  WHACK_OPT_FORCE_BUSY=>     bool,
  WHACK_OPT_CERT_SEND=>      bool,
  WHACK_OPT_STRICT_CRL_POLICY=> bool,
  WHACK_OPT_NO_RETRANSMITS=> bool,
  WHACK_OPT_CRL_CHECK_INTERVAL=> bool,
  WHACK_OPT_OCSPURI=>        tstr,
  WHACK_OPT_UNIQUE_IDS=>     bool,
  WHACK_OPT_USE_INTERFACE=>  tstr,
  WHACK_OPT_IKE_PORT=>       uint,
  WHACK_OPT_CTRL_BASE=>      tstr,
  WHACK_OPT_SHARED_SECRETS_FILE=> tstr,
  WHACK_OPT_IPSEC_DIR=>      tstr,
  WHACK_OPT_PERPEER_LOGDIR=> tstr,
  WHACK_OPT_PERPEER_ENABLED=> bool,
  WHACK_OPT_NAT_TRAVERSAL=>  bool,
  WHACK_OPT_NAT_KEEP_ALIVE=> uint,
  WHACK_OPT_NAT_FORCE_KEEP_ALIVE=> bool,
  WHACK_OPT_NAT_PORT_FLOAT=> bool,
  WHACK_OPT_VIRTUAL_PRIVATE=> tstr,
  WHACK_OPT_SET            => uint,
  WHACK_OPT_RECORDFILE     => tstr,
  WHACK_OPT_LISTEN_ON_LINK_SCOPE => bool,
}

InitiateOppo = {
  WHACK_OPT_OPPO_MY_CLIENT=>   IPaddress,
  WHACK_OPT_OPPO_PEER_CLIENT=> IPaddress,
}

IPaddress = #6.260(v6addr) / #6.261(v4addr)
IPsubnet  = #6.260([prefixlen, v6addr])
          / #6.261([prefixlen, v4addr])

prefixlen = uint
v6addr    = bytes .size 16
v4addr    = bytes .size 4

; the value literals for the keys.

WHACK_STATUS =  1
WHACK_SHUTDOWN =2
WHACK_OPTIONS  =3
WHACK_CONNECTION=4
WHACK_ROUTE    =5
WHACK_UNROUTE  =6
WHACK_INITIATE =7
WHACK_INITIATE_OPPO=8
WHACK_TERMINATE=9
WHACK_ADD_KEY  =10
WHACK_DELETE   =11
WHACK_LISTEN   =13
WHACK_UNLISTEN =14
WHACK_LIST     =15
WHACK_PURGE_OCSP=16
WHACK_REREAD   =17
WHACK_MYID     = 22
WHACK_DELETESTATE=23
WHACK_CRASHPEER=24
WHACK_ASYNC    =25
WHACK_NOOP     =99

WHACK_OPT_NAME = 1
WHACK_OPT_DEBUGGING = 2

WHACK_OPT_LEFT     = 3
WHACK_OPT_RIGHT    = 4

WHACK_OPT_IKE      = 5
WHACK_OPT_ESP      = 6

WHACK_OPT_LIFETIME_IKE = 146
WHACK_OPT_LIFETIME_IPSEC=147
WHACK_OPT_LIFETIME_REKEY_MARGIN=148
WHACK_OPT_LIFETIME_REKEY_FUZZ=149
WHACK_OPT_LIFETIME_REKEY_TRIES=150
WHACK_OPT_POLICY        = 127
WHACK_OPT_POLICYLABEL   = 128
WHACK_OPT_SET           = 129
WHACK_OPT_RECORDFILE    = 130
WHACK_OPT_OPPO_MY_CLIENT = 143
WHACK_OPT_OPPO_PEER_CLIENT=144
WHACK_OPT_KEYVAL        = 15
WHACK_OPT_KEYID         = 16
WHACK_OPT_KEYALG        = 17
WHACK_OPT_END_ADDR_FAMILY=18

WHACK_OPT_CONNALIAS      = 21

WHACK_OPT_DPD_DELAY      = 181
WHACK_OPT_DPD_TIMEOUT    = 182
WHACK_OPT_DPD_ACTION     = 183
WHACK_OPT_DPD_COUNT      = 184

WHACK_OPT_COREDIR    = 151
WHACK_OPT_NHELPERS   = 152
WHACK_OPT_SECCTX     = 153
WHACK_OPT_FORKDESIRED= 154
WHACK_OPT_STDERR_DESIRED=155
WHACK_OPT_LOG_WITH_TIMESTAMP=156
WHACK_OPT_KERN_INTERFACE=157
WHACK_OPT_SET_DEBUGGING =158
WHACK_OPT_LISTENADDR = 159
WHACK_OPT_ADD_DEBUGGING =160
WHACK_OPT_SAME_ADDR_OK = 161
WHACK_OPT_FORCE_BUSY = 162
WHACK_OPT_CERT_SEND  = 163
WHACK_OPT_STRICT_CRL_POLICY = 164
WHACK_OPT_NO_RETRANSMITS = 165
WHACK_OPT_CRL_CHECK_INTERVAL = 166
WHACK_OPT_OCSPURI    = 167
WHACK_OPT_UNIQUE_IDS = 168
WHACK_OPT_USE_INTERFACE = 169
WHACK_OPT_IKE_PORT   = 170
WHACK_OPT_CTRL_BASE  = 171
WHACK_OPT_SHARED_SECRETS_FILE = 172
WHACK_OPT_IPSEC_DIR  = 173
WHACK_OPT_PERPEER_LOGDIR = 174
WHACK_OPT_PERPEER_ENABLED= 175
WHACK_OPT_NAT_TRAVERSAL  = 176
WHACK_OPT_NAT_KEEP_ALIVE = 177
WHACK_OPT_NAT_FORCE_KEEP_ALIVE = 178
WHACK_OPT_NAT_PORT_FLOAT = 179
WHACK_OPT_VIRTUAL_PRIVATE= 180
WHACK_OPT_LISTEN_ON_LINK_SCOPE = 181

WHACK_OPT_END_ID   = 5
WHACK_OPT_END_CERT = 6
WHACK_OPT_END_CA   = 7
WHACK_OPT_END_GROUPS =8
WHACK_OPT_END_VIRT = 9
WHACK_OPT_END_XAUTH_NAME =137
WHACK_OPT_END_HOST_ADDRNAME = 10
WHACK_OPT_END_HOST_ADDR     = 11
WHACK_OPT_END_HOST_NEXTHOP  = 12
WHACK_OPT_END_HOST_SRCIP    = 13
WHACK_OPT_END_CLIENT        = 14

WHACK_OPT_HOST_TYPE = 15
WHACK_OPT_KEYTYPE   = 16
WHACK_OPT_HAS_CLIENT= 17
WHACK_OPT_HAS_CLIENT_WILDCARD=18
WHACK_OPT_HAS_PORT_WILDCARD=19
WHACK_OPT_HOST_PORT=20
WHACK_OPT_PORT=138
WHACK_OPT_XAUTH_SERVER=139
WHACK_OPT_XAUTH_CLIENT=140
WHACK_OPT_MODECFG_SERVER=141
WHACK_OPT_MODECFG_CLIENT=142
WHACK_OPT_CERTPOLICY=143
WHACK_OPT_CERTTYPE=144
WHACK_OPT_TUNDEV=145
