int sysctl_ip_default_ttl = 64;
int sysctl_ipsec_inbound_policy_check = 1;
int debug_tunnel;
int debug_xmit;
int debug_xform;
int debug_eroute;
int debug_spi;
int debug_radij;
int debug_pfkey;
int debug_ah;
int debug_rcv;
int debug_esp;
int debug_netlink;
int sysctl_ipsec_debug_verbose;
int sysctl_ipsec_debug_ipcomp;
int sysctl_ipsec_icmp;
int sysctl_ipsec_tos;
