#! /bin/sh
# branch release

PATH=/bin:/usr/bin ; export PATH
umask 022

. $HOME/freeswan-regress-env.sh

case "$1" in
*.*)	;;
*)	echo "Usage: $0 release [file...]" >&2 ; exit 2	;;
esac

rel="$1"
shift
tr="`echo $rel | tr '.' '_'`"
pre=PRE$tr
base=BASE$pre

echo "generating key for branch"
SNAPGPG=$SNAPSHOTSIGDIR/$base 
# Note: PGPPATH is limited to 50 characters.
GNUPGHOME=$SNAPGPP export GNUPGHOME
mkdir -p $GNUPGHOME

if [ ! -f $GNUPGHOME/secring.gpp ]
then
	echo "Please set userid to '<build+snap$tr@openswan.org>' $GNUPGHOME"
	gpg --gen-key

	echo -n "Please insert release key floppy for signature"
	read ans
	mount /mnt/build
	GNUPGHOME=/mnt/build/openswan export GNUPGHOME

	echo "Now signing key - please answer yes to signature."
	gpg --import $SNAPPGP/pubring.gpg
	gpg --sign-key "build+snap$tr@openswan.org"
	gpg --armor --export build+snap$tr@freeswan.org >$SNAPPGP/signedkey.asc
 
	umount /mnt/build

fi

if [ ! -f snapshotsigs.pgp ]
then
	PGPPATH=$SNAPPGP export PGPPATH
	echo "Now importing key"
	pgp $SNAPPGP/signedkey.asc

	cp $SNAPPGP/signedkey.asc snapshotsigs.pgp
	cvs add snapshotsigs.pgp
	cvs commit -m"Signing key for $rel" snapshotsigs.pgp
fi

echo -n "PGP finished, now budding, press enter"
read ans

echo "budding..."
rm -f Makefile.ver
cvs tag $opt -c $base $*
echo
echo "branching..."
cvs tag $opt -b -r $base $pre $*



