#!/bin/sh

refname=${1#refs/heads/}
[ "$refname" = "master" ] && refname=
oldhead=$2
newhead=$3
for merged in $(git-rev-list $newhead ^$oldhead | tac); do
	/public/scm/openswan.public/.git/ciabot.pl $merged $refname
done

touch /public/scm/openswan.public/.git/last-update
