#!/bin/sh

exec 1>&2
set -x

refname=${1#refs/heads/}
[ "$refname" = "master" ] && refname=
shift

for merged in $*; do
        /xelerance/MASTER/git-master/openswan.git/.git/ciabot.pl $merged $refname
done

touch /xelerance/MASTER/git-master/openswan.git/.git/last-update

