# -*- makefile -*-
CONNNAME=alttunnel
ENDNAME=h2h
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}
UNITTEST1PCAP=OUTPUT/h2hR2.pcap
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME} ${UNITTEST1PCAP} ../lp72-alg-h2hR1/h2hI1.pcap h2hI2.pcap

TESTNAME=h2hR2

pcapupdate:
	cp ../lp73-alg-h2hI2//OUTPUT/h2hI2.pcap .
