.\"     Title: _PLUTOLOAD
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/14/2008
.\"    Manual: 25 Apr 2002
.\"    Source: 25 Apr 2002
.\"
.TH "_PLUTOLOAD" "8" "11/14/2008" "25 Apr 2002" "25 Apr 2002"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ipsec _plutoload - internal script to start pluto
.SH "DESCRIPTION"
.PP
\fI_plutoload\fR
is called by
\fB_plutorun\fR
to actually start the pluto executable\.
.SH "SEE ALSO"
.PP
\fBipsec\fR(8),
\fBipsec_setup\fR(8),
\fBipsec__realsetup\fR(8),
\fBipsec__plutorun\fR(8)
.SH "HISTORY"
.PP
Man page written for the Linux FreeS/WAN project <\fIhttp://www\.freeswan\.org/\fR> by Michael Richardson\. Original program by Henry Spencer\.
