'\" t
.\"     Title: _PLUTOLOAD
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 10/06/2010
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "_PLUTOLOAD" "8" "10/06/2010" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ipsec__plutoload \- internal script to start pluto
.SH "DESCRIPTION"
.PP
\fI_plutoload\fR
is called by
\fB_plutorun\fR
to actually start the pluto executable\&.
.SH "SEE ALSO"
.PP
\fBipsec\fR(8),
\fBipsec_setup\fR(8),
\fBipsec__realsetup\fR(8),
\fBipsec__plutorun\fR(8)
.SH "HISTORY"
.PP
Man page written for the Linux FreeS/WAN project <\m[blue]\fBhttp://www\&.freeswan\&.org/\fR\m[]> by Michael Richardson\&. Original program by Henry Spencer\&.
