# -*- makefile -*-
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/hostpair.o
SAMPLEDIR=../../../functional/10-defaultroute
WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}
ENDNAME=bob
CONNNAME=nat-t
UNITTESTARGS=${WHACKFILE} ${CONNNAME}

TESTNAME=loadbob
