# -*- makefile -*-

WHACKFILE=${OUTPUTS}/ikev2client.record.${ARCH}
# use a broken end connection that selects a different cipher to
# force NOPROPOSALCHOSEN.
CONNNAME=parker1--jj2--wrong
UNITTEST1ARGS=${WHACKFILE} ${CONNNAME} OUTPUT/parentR2.pcap parentI1.pcap parentI2.pcap

ENDNAME=parker

TESTNAME=parentR2

PCAPDEPENDENCIES = ../lp02-parentI1/OUTPUT/parentI1.pcap
PCAPDEPENDENCIES+= ../lp10-parentI2/OUTPUT/parentI2.pcap
include ../Makefile.pcapupdate

pcapupdate: ${PCAPDEPENDENCIES}
	@for pcap in ${PCAPDEPENDENCIES}; do cp $$pcap $$(basename $$pcap); done

