include ../lp14-initiateself/Makefile
EXTRAOBJS+=${OBJDIRTOP}/programs/pluto/x509keys.o
include Makefile.testcase


# Local Variables:
# compile-command: "make check"
# gdb-command: ""
# End Variables:
#
